### ISSUE TITLE
Fast channel selection mode with subset names

### ISSUE THREAD

**Issue by bernerha** [matterhorn-chat/matterhorn#284] opened 2017-07-17 07:42 UTC
Hey,
it isn't possible to coose a channel with the name "channel1" if there's another channel with the name "channel1channel" because the first channel is a subset of the second.
A selection in the fast channel selection would be nice.

Cheers

**Comment by jtdaugherty** [comment] 2017-07-17 15:09
This is a duplicate of #81. Thanks for the ticket!

**Closed by jtdaugherty** 2017-07-17 15:09 UTC

**Comment by kquick** [comment] 2017-07-17 16:15
@bernerha, while issue #81  captures the select enhancement, you do have the ability to select channel1 even in the current versions.  Prior to our 31000.0.0 release (https://github.com/matterhorn-chat/matterhorn/releases/tag/31000.0.0) it was relatively undocumented but you can use the carat (`^`) to restrict the match to the start of the name, and (`$`) to mark the end of the name (similar to a regex, but it's not a full regex, it only recognizes these two special characters).

In the 31000.0.0 release, this information is added to the channel select prompt, and 31000.0.0 also includes an enhancement that will select the channel if you've specified it exactly, even if there are longer matches.

For your example, channel select of `channel1$` or even `1$` would work, and in 31000.0.0, the exact `channel1` would also work.

**Comment by bernerha** [comment] 2017-07-18 06:51
@kquick whoa, nice to know 👍
