### ISSUE TITLE
Matterhorn appears to not respect 'mute channel' setting

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#585] opened 2020-04-01 21:59 UTC
If I set a channel to 'muted' in the 'Notification Preferences' on the Mattermost web UI, the channel won't trigger as 'unread' unless I'm mentioned.  Matterhorn, unfortunately doesn't appear to respect this setting and the channel still highlights as 'unread' and M-a will switch me to it.

I'm using matterhorn-50200.8.0-ubuntu-18.04-bionic-x86_64.tar.bz2.  The server version is 5.21.0.

**Comment by jtdaugherty** [comment] 2020-04-01 22:37
Thanks for the report! That suggests those settings are client-enforced, not server-enforced (as I would expect and hope), so we will definitely need to investigate. I'm going to close this as a slight duplicate of https://github.com/matterhorn-chat/matterhorn/issues/582 but I'll make a note on that ticket to be sure to follow up on this.

**Closed by jtdaugherty** 2020-04-01 22:37 UTC
