### ISSUE TITLE
Change backspace from DEL to Ctrl-H?

### ISSUE THREAD

**Issue by morsedl** [matterhorn-chat/matterhorn#565] opened 2020-02-20 09:45 UTC
Hi,

I'm on Ubuntu 16.04 (and cannot upgrade anytime soon), so I'm stuck on older version for the time being (see below). Unfortunately, this version does not have the `-k` option (IIRC) to dump the keyboard mapping to stdout. I've even gone so far as to try to build from sources to get the latest version working on Ubuntu 16.04 but ran into all sorts of problems with cabal (something about one part of being built with one version of cabal and another part with another, so things won't work and build can't finish, despite the fact that I know only one cabal is installed).

My question: How can I change the keymapping in this version so that CTRL-H (ASCII character 8) deletes the character left of the cursor rather than DEL (ASCII character 127)?

Thank you kindly in advance for your assistance.

Cheers,
Doug

```
$ matterhorn --version
matterhorn 50200.1.2 (master@f4aea40)
 using mattermost-api 50200.1.1 (HEAD@e13b17b)
```

**Comment by jtdaugherty** [comment] 2020-02-20 18:40
As far as changing the keybindings, you can find help for how to do that by running `/help keybindings`. That help content discusses how to go about creating a custom keybinding file.

As far as the specific behavior you cited is concerned, I'm actually really surprised by your report, because in all of the terminal emulators I've tested Matterhorn with, `C-h` does what you describe. For me, on Mac OS and using iTerm2, Matterhorn has always deleted the character to the left of the cursor with a manual keypress of `C-h` or the `Backspace` key, and the `Delete` key deletes the character at the current cursor position. Out of curiosity, what sort of terminal emulator environment are you using?

**Comment by morsedl** [comment] 2020-02-24 16:48
Hi Jonathan,

My apologies for the slow reply, things have been quite busy.

First and foremost, thanks for your help!

Second, to answer your question: Terminator (Python-based):

```
$ dpkg -l | grep terminator
ii  terminator                                                  1.90+bzr-1705-1                                          all          multiple GNOME terminals in one window
```

and the context:

```
$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
$ stty -a
speed 38400 baud; rows 59; columns 225; line = 0;
intr = ^C; quit = ^\; erase = ^H; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

**Comment by jtdaugherty** [comment] 2020-02-24 16:50
Do you experience the undesired behavior with other terminal emulators on the same system?

**Comment by morsedl** [comment] 2020-02-24 17:07
Yes, unfortunately. Gnome Terminal. Same problem: Ctrl-H / Backspace does nothing, DEL deletes the character to the left of the cursor.

```bash
$ morse@n1 ~> stty
speed 38400 baud; line = 0;
erase = ^H;
-brkint -imaxbel iutf8
morse@n1 ~> dpkg -l gnome-terminal
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                                                      Version                           Architektur                       Beschreibung
+++-=========================================================-=================================-=================================-========================================================================================================================
ii  gnome-terminal                                            3.18.3-1ubuntu1                   amd64                             GNOME terminal emulator application
morse@n1 ~>
```

**Comment by jtdaugherty** [comment] 2020-02-24 17:09
What kind of keyboard are you using?

**Comment by jtdaugherty** [comment] 2020-02-24 17:09
It's also possible your choice of keyboard layout is governing the key behavior.

**Comment by jtdaugherty** [comment] 2020-02-24 17:09
(Keyboard layout choice as the window manager or OS level, I mean.)

**Comment by morsedl** [comment] 2020-02-24 17:10
Das Keyboard 4 Pro, german layout.

No, I'm sure the problem is not the keyboard. I don't have this problem with any other ncurses-based CLI program.

**Comment by jtdaugherty** [comment] 2020-02-24 17:10
Also: do you have this problem in other applications, terminal or graphical?

**Comment by morsedl** [comment] 2020-02-24 17:15
Nope, not having this problem elsewhere.

Just FYI: I've 35-years programming experience and started off with SCO Xenix (286 chip). Lot's of experience with real terminals (e.g., Wyse 60) and all sorts of terminal emulators. So I'm quite familiar with how CLI apps work.

Also, TERM=xterm-256color was for both tests (Terminator and Gnome Terminal)

**Comment by morsedl** [comment] 2020-02-24 17:16
The problem I'm having is that I cannot find anywhere (e.g., with `/help keybindings`) the string I need to use to indicate delete one character left.

**Comment by jtdaugherty** [comment] 2020-02-24 17:17
> So I'm quite familiar with how CLI apps work.

That's great to know. I hope it's clear that any questions I ask are not intended to suggest otherwise, but more for out of a desire to ensure that the problem is investigated fully. Even obvious details should be considered, since as you have surely experienced, it is too often the obvious issues that turn out to be the problem.

> The problem I'm having is that I cannot find anywhere (e.g., with /help keybindings) the string I need to use to indicate delete one character left.

That's because that behavior is not rebindable. We have never encountered a situation where it didn't work as intended and we haven't felt the need to make it customizable, so there is currently no way to rebind it.

**Comment by morsedl** [comment] 2020-02-24 17:19
Ah. Well that certainly explains why I am not finding the setting. :-)

**Comment by jtdaugherty** [comment] 2020-02-24 17:22
On MacOS where the backspace behavior works as intended, I have:
```
$ stty -a
speed 9600 baud; 43 rows; 173 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
        -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
        -extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel -iutf8
        -ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
        -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
        eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
        min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
        stop = ^S; susp = ^Z; time = 0; werase = ^W;
```
I'm not sure what to make of the difference for `erase`.

**Comment by morsedl** [comment] 2020-02-24 17:32
That means erase character is mapped to ASCII 127, which is quite often mapped to Backspace with a lot of terminal emulators. It's rather replaced ASCII 8 (CTRL-H) as they character sent by Backspace. But a lot of us older folk stick with Ctrl-H for Backspace key and DEL for Delete key. Pressing either Ctrl-H nor Backspace (to which both I have both Terminator and Gnome Terminal configured).

Interesting, however:

TERM=

ansi: works, but cursor is invisible
vt110: works, but display is corrupt (but usable enough to test Backspace)
vt220: works, but no color, no cursor
linux: doesn't work
xterm doesn't work
xterm-256color doesn't work
scoansi: doesn't work, display corrupt

**Comment by morsedl** [comment] 2020-02-24 17:34
These are all standard, Ubuntu 16.04 LTS terminfo files.

**Comment by morsedl** [comment] 2020-02-24 17:35
I'm thinking that Matterhorn may not be allowing stty settings to override what's specified in terminfo.

**Comment by morsedl** [comment] 2020-02-24 17:41
I think I can get by with running as `TERM=ansi mattermost` so at least Backspace works for me, although not having the cursor visible isn't ideal.

It does seem though that the problem is termcap / terminfo related, as things works with TERM=ansi but not the others (with `stty erase` always set to Ctrl-H (ASCII 8) and the emulator always sending that when the Backspace key is pressed).

I suspect the long-term solution is simply to allow users to configure a delete-character-left token (keyboard key in Matterhorn) as well. Probably not a high demand for this, as, as noted, most emulators default to DEL (ASCII 127) for the Backspace key and not so many people change this, but something important to be able to configure in any CLI app.

**Comment by jtdaugherty** [comment] 2020-02-24 17:42
We're investigating this on our end as well, and I'm also fairly certain that Matterhorn's underlying terminal I/O library isn't picking up those overrides. The fix is definitely to make it respect the overrides.

**Comment by jtdaugherty** [comment] 2020-02-24 17:43
(I am the maintainer for that library, so we have a fast path to fixing this.)

**Comment by morsedl** [comment] 2020-02-24 17:48
K, great to hear!

I kind of sensed the Mattermost team might not be completely familiar with the interaction between ttys / psuedo-ttys and the termcap / terminfo libraries because of the use of Ctrl-S to select message to which to reply, to delete, etc. In the "old school", "real" terminal days, Ctrl-S and Ctrl-Q were used for flow control (as then you could quite easily overflow a terminal's incoming serial buffer) and thus often greatly avoided in then CLI apps ("then" because that's mostly all there was), as a user pressing Ctrl-S accidentally would "freeze" their screen and then often result in a support call, which often quickly ended with "Try pressing Ctrl-Q. Everything working? Super, glad I could help." ;-)

**Comment by jtdaugherty** [comment] 2020-02-24 17:52
Actually we are completely aware of those bindings and their uses! But they are so infrequently used (or needed) that we figured using them for application purposes would not lead to confusion for most users, with the upside that we got two bindings that had better mnemonics than the alternatives. 😊

As for the problem at hand, the issue, in summary, is that Matterhorn (like many TUI applications) runs with canonical mode disabled.

**Comment by morsedl** [comment] 2020-02-24 17:52
Well, I think I'm OK for now. I'll let you core developers get this resolved. If I can be of any help, however, do LMK. The first O'Reilly book I bought was "Termcap & Terminfo", back in '88 or so. Still have it. So although I cannot make a patch and pull request due to many active, pressing deadlines, I can certainly be a resource should you need it.

Again, thanks for matterhorn, and your help!

**Comment by morsedl** [comment] 2020-02-24 17:53
> Actually we are completely aware of those bindings and their uses! But they are so infrequently used (or needed) that we figured using them for application purposes would not lead to confusion for most users, with the upside that we got two bindings that had better mnemonics than the alternatives. 
> 
> As for the problem at hand, the issue, in summary, is that Matterhorn (like many TUI applications) runs with canonical mode disabled.

Hmm... interesting. I've never heard respecting stty line settings as "canonical mode", but that certainly makes sense.

**Comment by jtdaugherty** [comment] 2020-02-24 17:55
https://www.gnu.org/software/libc/manual/html_node/Canonical-or-Not.html

> In canonical input mode, the operating system provides input editing facilities: some characters are interpreted specially to perform editing operations within the current line of text, such as ERASE and KILL. See Editing Characters.

As best we can tell, `stty` is what governs how ERASE, for example, is interpreted. If canonical mode is disabled, the bindings set up in `stty` have no effect.

**Comment by jtdaugherty** [comment] 2020-02-24 17:56
> the bindings set up in stty have no effect

Well, at least the bindings that are interpreted in canonical mode.

**Comment by morsedl** [comment] 2020-02-24 18:00
That's correct. As I said, the phrase "canonical mode" is new to me, but GNU is obviously a rather definitive source. And based on that, I can say for 100% certain that the `stty` command is precisely the one that one uses to bind characters (among other things) in canonical mode. A common command I've had to run in the past is `stty erase ^H` (where the "^H" portion is an actual ASCII 8 character typed in at the bash prompt with `Ctrl-V, Ctrl-H`.

**Comment by jtdaugherty** [comment] 2020-02-24 20:34
Out of curiosity: what is preventing you from upgrading Matterhorn? Will our newer builds not run on 16.04 due to e.g. runtime linking issues?

**Comment by jtdaugherty** [comment] 2020-02-24 21:58
Also, it turns out there *is* a way to get the behavior you want without a functionality change in `matterhorn` (and that will work with your current version):

Make a new file, `~/.vty/config`, and give it the following content:
```
map _ "\BS" KBS []
```
That configuration will cause `C-h` (ASCII 8) to cause a "backspace" event (`KBS`) in the Vty library's input processing logic, which will get the desired behavior in Matterhorn regardless of terminal type. Thanks to @glguy for pointing that out.

The `\BS` sequence is taken from [the table that documents Haskell string literal escapes for various special characters](http://book.realworldhaskell.org/read/characters-strings-and-escaping-rules.html), which is what the Vty library uses to parse the string literal in the line above (see Table B.2.).

Even though that should get you want you want, I'm still working on a patch to Vty to ask the kernel about what `stty`'s `erase` character is, and then honor that when handling input in the case where no custom configuration is provided.

**Comment by morsedl** [comment] 2020-02-25 13:58
@jtdaugherty @glguy : 

Thank you kindly! That workaround indeed works on my Ubuntu 16.04 LTS installs.

I look forward to the update (at whatever point I can upgrade the underlying OS).

**Comment by morsedl** [comment] 2020-02-25 14:02
> Out of curiosity: what is preventing you from upgrading Matterhorn? Will our newer builds not run on 16.04 due to e.g. runtime linking issues?

Correct:

```bash
morse@n1 matterhorn-50200.6.0-ubuntu-18.04-bionic-x86_64> l ./matterhorn 
-rwx------ 1 morse morse 50003920 Jan 15 18:01 ./matterhorn
morse@n1 matterhorn-50200.6.0-ubuntu-18.04-bionic-x86_64> file matterhorn 
matterhorn: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=f0c75ff82ec4b847f27e3488cdcff8ed1db92b65, stripped
morse@n1 matterhorn-50200.6.0-ubuntu-18.04-bionic-x86_64> ldd matterhorn 
./matterhorn: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./matterhorn)
	linux-vdso.so.1 =>  (0x00007ffdf0377000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa655757000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa65553a000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fa655311000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa655108000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fa654f05000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa654d01000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fa654a80000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa654777000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fa65456f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6541a4000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f486ff7000)
morse@n1 matterhorn-50200.6.0-ubuntu-18.04-bionic-x86_64> ./matterhorn 
./matterhorn: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./matterhorn)
morse@n1 matterhorn-50200.6.0-ubuntu-18.04-bionic-x86_64> 
```

**Comment by jtdaugherty** [comment] 2020-02-25 15:58
Okay, I'm glad to hear that you now have the behavior you were looking for. Can you please confirm that you have everything you need by closing this ticket, or letting me know what we missed?

**Comment by morsedl** [comment] 2020-02-25 16:43
Sure thing, gladly. But it appears I cannot. Github error is "You can't 
comment at this time." Nor can I close the ticket.


Am 25.02.2020 um 16:58 schrieb Jonathan Daugherty:

**Comment by jtdaugherty** [comment] 2020-02-25 17:17
Okay, strange. I'll close it. Thanks!

**Closed by jtdaugherty** 2020-02-25 17:17 UTC

**Comment by jtdaugherty** [comment] 2020-02-27 19:00
This is now supported natively in `develop` and will be included in the next release. Beyond that point, the Vty config described above will not be needed to support `stty erase`.
