### ISSUE TITLE
could not reach server when network proxy is configured.

### ISSUE THREAD

**Issue by prabhu-madanagopal** [matterhorn-chat/matterhorn#317] opened 2017-09-09 09:04 UTC
When network (corporate) proxy is configured, login error: could not reach server. 
Could matterhorn read the below environment variables and connect to server using proxy?
ALL_PROXY
HTTP_PROXY
HTTPS_PROXY

**Comment by jtdaugherty** [comment] 2017-09-09 15:02
This is a duplicate of #302.

**Closed** 2017-09-09 15:02 UTC
