### ISSUE TITLE
subtle issue with usernames that contain periods and share a common prefix

### ISSUE THREAD

**Issue by jclulow** [matterhorn-chat/matterhorn#373] opened 2018-03-16 18:34 UTC
Our Mattermost instance is backed by our corporate LDAP directory, and most usernames are of the form "firstname.lastname".  Some older accounts are just "firstname", though that obviously stopped being tenable once we hit the first collision.

In this case, there is an account (e.g., "john") and another account (e.g., "john.citizen").  The colouring of usernames always seems to prefer "john" rather than "john.citizen", so only the word "john" is highlighted leaving a subsequent ".citizen" in plain text afterwards.

In recent builds this has become more acute, because "john" is not in the channel I'm using but "john.citizen" is.  When I use @ to refer to "john.citizen" I now get the "john was mentioned but is not in the channel" message.

It seems like perhaps the period is in some secondary character class which is less "sticky" for matches than alphanumeric characters?

**Comment by jtdaugherty** [comment] 2018-03-16 18:35
Thanks for the report. This is essentially a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/291. We can escalate it.

**Closed by jtdaugherty** 2018-03-16 18:35 UTC

**Comment by jclulow** [comment] 2018-03-16 18:42
Thanks, I'm sorry I missed that one in my issue search.

**Comment by jtdaugherty** [comment] 2018-03-16 18:43
No problem - admittedly it was not easy to tell that it's another symptom of the same issue.
