### ISSUE TITLE
Let's Encrypt CA not in trust anchor

### ISSUE THREAD

**Issue by southerntofu** [matterhorn-chat/matterhorn#607] opened 2020-04-19 23:45 UTC
After building on Debian stable i want to try on a server but i get this error:

```
Error: HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))
```

I believe this is a problem with a dependency and not with the project itself but i'm not familiar with the Haskell ecosystem so i'm reporting the issue so you can either update your deps or open an issue upstream

**Comment by jtdaugherty** [comment] 2020-04-20 00:06
This is a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/576 and is an issue with the system certificate bundle missing the LetsEncrypt CA certificate.

**Closed by jtdaugherty** 2020-04-20 00:06 UTC
