### ISSUE TITLE
Changing channels creates a lot of HTTPResponseException errors

### ISSUE THREAD

**Issue by scottleedavis** [matterhorn-chat/matterhorn#508] opened 2019-07-16 20:08 UTC
This is on OSX, using 50200.4.0
![Screen Shot 2019-07-16 at 1 08 02 PM](https://user-images.githubusercontent.com/2914443/61326027-cdd48480-a7ca-11e9-9db2-d6b236141c84.png)

**Comment by jtdaugherty** [comment] 2019-07-16 20:10
Thanks for the report! This is a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/504. Please take a look at that ticket, and contact your server admin to increase your API request limit. We haven't gotten around to improving how Matterhorn deals with this yet, but we will in that other ticket.

**Closed by jtdaugherty** 2019-07-16 20:10 UTC
