### ISSUE TITLE
Optimistic display of your own messages

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#610] opened 2020-04-23 15:53 UTC
In Matterhorn, after I hit return, especially when I paste a URL, there is a noticeable lag (1-2 seconds) before my message appears in channel.  This doesn't happen on the Web UI or IOS app.  According to #mattermost this is because the Web UI and IOS App are optimistic and assume the message you sent will go through and displays it locally immediately.  It would be really nice (for me) if Matterhorn could do the same.  The delay in seeing what I typed appear in channel causes weird cognitive dissonance for me.

**Comment by jtdaugherty** [comment] 2020-04-23 16:24
I discussed this with Harrison H. on the server development team. For posterity, if we decide to go forward with this, this is how the web client accomplishes this and how Matterhorn will also have to proceed:

* Clients set the `pending_post_id` of the post when making the post creation API calls. The value can be an arbitrary string (apparently of unlimited length). The value is never inspected or stored by the server. It is just a client-side token identifying the post.
* When the server responds to the post creation API request, it includes the `pending_post_id` in the response.
* When the server sends out the websocket event for the new post, it *also* includes the `pending_post_id` in that message, giving clients the ability to identify events about new posts that they had previously submitted.
* The server apparently uses the `pending_post_id` to deduplicate requests across clients for the same user account, so it's important that clients use a sufficiently unique ID generation scheme such as UUID generation for this value.

**Comment by jtdaugherty** [comment] 2020-04-23 16:30
Apparently the web client uses `<user_id>:<timestamp>` as its `pending_post_id` scheme. And apparently the deduplication scheme is mostly to avoid duplicate messages from the *same* client. Still, we could generate one UUID at startup for the client and go with `<uuid>:<user_id>:<timestamp>` and avoid any potential for collision.

**Comment by jtdaugherty** [comment] 2020-04-23 16:39
A couple of other things that need to be considered:
* We need to decide how to present messages that have not been confirmed by the server.
* We also need to be prepared to handle message re-ordering:
  * Local user sends message A and displays it as the next anticipated message in the channel.
  * Remote user sends message B.
  * Message B arrives apparently *after* A.
  * Message A arrives from the server but is after B once the timestamps are analyzed.

Our current message management data structure will handle re-ordering *for free*: the problem to solve isn't to support reordering from a data management perspective, but from a UI perspective. When the anticipated message is put into the message sequence for the channel, a server timestamp will have to be synthesized. But when the final message arrives, its *actual* server timestamp will likely differ (leading to the potential for reordering as described above).

**Comment by jtdaugherty** [comment] 2020-04-23 16:56
Another point via @kquick: once the message arrives it'll be necessary to update its creation timestamp based on the one from the server.

**Comment by spidey** [comment] 2020-08-18 09:37
What about using the timestamp as an indication that the server hasn't accepted the message yet? Leave it as ??:??, for example. Or maybe mess with the separators, changing `[]` for `!!` while the message is not accepted.

**Comment by jtdaugherty** [comment] 2023-04-14 03:23
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.

**Closed by jtdaugherty** 2023-04-14 03:23 UTC
Labels: enhancement, feature parity, investigate
