### ISSUE TITLE
"Disconnected. Will refresh when connected."

### ISSUE THREAD

**Issue by daveman1010221** [matterhorn-chat/matterhorn#535] opened 2019-10-09 13:15 UTC
The client seems to disconnect from the server quite often and display this message. Is this normal behavior? Should I be concerned about this? Sending messages seems to take a while with this behavior.

**Comment by kquick** [comment] 2019-10-09 15:47
This is generally indicative of an unstable network connection.  There is a websocket connection maintained between Matterhorn to receive updates from the server, and the above message is displayed when that websocket disconnects.  Matterhorn will handle reconnecting and resuming when connectivity is available, and it will queue local messages to send when connectivity has been re-established.

I commonly see this message when I resume my laptop at work after having put it to sleep at home before heading to work, but it is short-lived and also not typical to see this message during the day.  You may want to check your system logs to see if there are connectivity-impacting events, and perhaps your VPN logs if you are on a VPN.

**Comment by jtdaugherty** [comment] 2019-10-09 16:23
@daveman1010221 what version of Matterhorn are you running when this happens?

**Comment by jtdaugherty** [comment] 2019-10-09 16:41
Actually, @daveman1010221, regardless of version: do you have user typing notifications enabled with the `showTypingIndicator = True` configuration setting?

**Comment by daveman1010221** [comment] 2019-10-09 17:59
Yes, showTypingIndicator = True is enabled.

I'm using the version I cloned as of Fri Sep 13 10:56:27 2019 -0700. 

I am on an ethernet connection, no VPN.

**Comment by jtdaugherty** [comment] 2019-10-09 18:09
Okay, thanks. For now you'll need to disable that setting due to [a bug](https://github.com/matterhorn-chat/matterhorn/issues/529) that we have not resolved yet. That should address your disconnection issue.

**Comment by jtdaugherty** [comment] 2019-10-09 18:26
Once @daveman1010221 confirms that this helps, I'll close this as a duplicate of #529.

**Comment by jtdaugherty** [comment] 2019-10-09 19:45
Okay, great! That confirms the issue, so I'll close this (see: #529). Thanks!

**Closed by jtdaugherty** 2019-10-09 19:45 UTC
