### ISSUE TITLE
ability to select channel within fast selection mode

### ISSUE THREAD

**Issue by amaloz** [matterhorn-chat/matterhorn#247] opened 2017-06-08 16:10 UTC
Suppose you have channels `~abc` and `~abcd`.  If you use fast selection mode to try to jump to channel `~abc`, the mode will display both channels and it's not possible to select between the two.  It'd be nice to have some keybinding that can select channels from this list.

**Comment by jtdaugherty** [comment] 2017-06-08 16:32
Thanks for the request! This is a duplicate of #81.

**Closed by jtdaugherty** 2017-06-08 16:32 UTC

**Comment by jtdaugherty** [comment] 2017-10-05 17:58
This is now supported in `develop` and will go out in the next release.
