### ISSUE TITLE
Meta not working as expected on xterm

### ISSUE THREAD

**Issue by ze42** [matterhorn-chat/matterhorn#698] opened 2021-03-04 16:01 UTC
On my configuration, `M-` won't work, as they send different characters into my terminal, so the application does not know I use my meta key (alt).

On other application (like shell), I tend to do `ESC <key>` to do that, and it works fine. Here, it cannot be done, because `ESC` as itself is already taken, and won't hold to know what comes next...

I tried configuring the caracter sent by `M-a`, but...

```
Configuration error: The keybinding `á` is bound to the event `focus-next-unread`
This is probably not what you want, as it will interfere with the ability to write messages!
```

Could you please make some option to bypass that check? I'm happy not to use those characters while typing in matterhorn, but don't want to have to change my keyboard configuration because of an application.

**Comment by jtdaugherty** [comment] 2021-03-04 16:31
Hi @ze42, there are probably other options we can investigate. What terminal emulator are you using?

**Comment by jtdaugherty** [comment] 2021-03-14 16:51
@ze42 I'd love to help you address this issue. Can you provide some more information about your environment? The best solution here will be to configure your terminal to send `Meta` when you press `Alt`. (For example, I do this myself with iTerm2.)

**Comment by ze42** [comment] 2021-03-19 13:09
Using `xterm`, and keymap via `setxkbmap 'us(intl)'`.

**Comment by jtdaugherty** [comment] 2021-03-19 17:20
Thanks, @ze42. I'll investigate!

**Comment by jtdaugherty** [comment] 2021-03-23 19:52
Hi @ze42, here is a configuration that may resolve your Meta issue. Assuming you do not need the current input behavior you're seeing, you can update your `~/.Xdefaults` with this:
```
XTerm*eightBitInput:   false
XTerm*eightBitOutput:  true
```
Source:
https://www.gnu.org/software/emacs/manual/html_node/efaq/Meta-key-does-not-work-in-xterm.html

I was able to reproduce your problem in `xterm` on macOS/Xquartz; the configuration above resolved the issue for me. The modifier keys did seem to indeed be generating `Meta` events (according to `xev` which you can also try), but the terminal input mode seems to be the culprit.

Let me know if that resolves this for you!

**Comment by jtdaugherty** [comment] 2021-03-29 17:07
@ze42 Have you had a chance to try this out?

**Comment by jtdaugherty** [comment] 2021-11-12 16:58
Hi @ze42 - since this has been quiet for a while, I'm going to close it. Please re-open if the above fix did not work for you. Thanks!

**Closed by jtdaugherty** 2021-11-12 16:58 UTC
