### ISSUE TITLE
Handling of threads

### ISSUE THREAD

**Issue by EugenMayer** [matterhorn-chat/matterhorn#541] opened 2019-10-28 07:53 UTC
Is there any way to show the messages of a thread or anything similar to this yet?
I can see that it is annotated in the channel that this is a thread answer ( to some thread ) and the first message / thread topic is displayed above, but there is no way to see all thread messages.

For me this would be very critical, following up on thread messages and reading them in a sequence is one of the critical features for us with mattermost.

Did i miss something obvious or are there any plans? Thanks

**Comment by jtdaugherty** [comment] 2019-10-28 15:12
Better handling of threads is definitely something we want to support. We have been exploring ideas about how to approach this for a while; for details, [see the wiki](https://github.com/matterhorn-chat/matterhorn/wiki/Conversation-View) for details. The features described there have been prototyped, but I have to point out that I don't know how likely it is that the prototype will be released.

Still, regardless of whether the prototype ends up being merged and released, we want to do *something* about this, even if it just means implementing something similar to what the web client provides. But unfortunately we won't have time to get to it in the near future.

I'm closing because this is a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/396. Thank you!

**Closed by jtdaugherty** 2019-10-28 15:12 UTC

**Comment by jtdaugherty** [comment] 2022-06-10 23:53
@EugenMayer FYI this is now done and will go out in the next release!
