### ISSUE TITLE
Cannot leave/delete multi-party direct message group

### ISSUE THREAD

**Issue by UlfS** [matterhorn-chat/matterhorn#245] opened 2017-06-08 14:35 UTC
I cannot find a way to leave or delete a multi-party direct message group (introduced with [mattermost 3.7.5](https://docs.mattermost.com/administration/changelog.html#group-messaging)).
The group is listed in my channel list with comma-separated names.
Issuing a leave command does not work:
```
The /leave command cannot be used with this channel.
```
Leaving the group in the official mattermost client  works, but it still shows up in matterhorn.
This is clutters up my channel list and makes it impossible to use C-g to switch to a particular person directly if he is/was a member of a group chat.

Also, matterhorn crashed upon joining/leaving a direct message group with the following message:
```hs
matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.event: Unknown websocket message: \"preferences_changed\"", jsonDecodeExceptionJSON = "{\"event\":\"preferences_changed\",\"data\":{\"preferences\":\"[{\\\"user_id\\\":\\\"...\\\",\\\"category\\\":\\\"group_channel_show\\\",\\\"name\\\":\\\"...\\\",\\\"value\\\":\\\"false\\\"}]\"},\"broadcast\":{\"omit_users\":null,\"user_id\":\"...\",\"channel_id\":\"\",\"team_id\":\"\"},\"seq\":42}"}
```

**Comment by jtdaugherty** [comment] 2017-06-08 16:35
Thanks for the report! This is partly a duplicate of #180. (In the future, please report bugs/crashes and feature requests as separate tickets; that will help us track things better!)

And the crash you mentioned is the same crash as mentioned elsewhere - a 3.9 feature not supported on matterhorn due to its support for (at most) 3.8 servers.

**Closed by jtdaugherty** 2017-06-08 16:35 UTC
