### ISSUE TITLE
URL in ephemeral message (from a custom slash command) not openable/clickable

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#638] opened 2020-07-08 16:54 UTC
Our server has a custom slash command /acronym that talks to a bot which looks up acronyms in a Google spreadsheet and decodes them for the user.  The reply comes to the user in the form of an ephemeral message which includes a URL.  In the web UI, I can click on the URL.  In Matterhorn, the link is not clickable (I have hyperlinkURLs set to True) and C-o doesn't show it.

I turned on logging and reproduced it, a lightly sanitized copy of which is here:

  https://paste.ubuntu.com/p/vhB6mTrsgJ/

**Comment by jtdaugherty** [comment] 2020-07-08 17:10
On investigation, this turns out to be because the function that gathers up URLs from incoming messages ignores messages with no source user (such as these ephemeral messages). I'm going to investigate changing that.

**Comment by jtdaugherty** [comment] 2020-07-08 17:15
This is now fixed in `develop` and will be included in the next release. Thank you for your report!

**Comment by jtdaugherty** [comment] 2020-07-08 17:20
@jtroup I am also curious - you said you had hyperlinking enabled, and yet the link in the message wasn't hyperlinked. Are hyperlinks working in other messages?

**Comment by jtroup** [comment] 2020-07-08 18:16
@jtdaugherty Hyperlinks are working on other messages.  In the ephemeral case, the visible text ('here' in my example) is orange, but if I mouse over it, it doesn't become a link.

**Comment by jtdaugherty** [comment] 2020-07-08 18:33
Okay, thanks - that might be a separate bug then! I'll investigate.

**Comment by jtdaugherty** [comment] 2020-07-08 18:46
I'm unable to reproduce the hyperlinking issue you mentioned, even without the above fix (which shouldn't impact that behavior anyway). Do working hyperlinks appear differently than other text in your terminal (aside from color)? For me, in iTerm2, hyperlinked text has a dotted underline that iTerm2 adds. Could you post a screenshot of one of these informative messages alongside a message that has a working hyperlink?

**Comment by jtroup** [comment] 2020-07-08 19:44
Sorry, maybe my terminal is doing the link conversion...  I'm currently using xfce4-terminal; let me try some others and confirm.

**Comment by jtdaugherty** [comment] 2020-07-15 17:03
@jtroup any update?

**Closed** 2020-08-13 22:01 UTC
Labels: bug
