### ISSUE TITLE
Add 'copy link' functionality for messages

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#660] opened 2020-08-31 14:02 UTC
The web UI offers a 'copy link' functionality for messages; it'd be nice if Matterhorn offered it too.  (I'm assuming the link is generated server side and available via the API)

FWIW, with our server, the link looks like this:

  https://$ON_PREM_MATTERMOST.com/$TEAM/pl/$26_CHAR_HASH

**Comment by jtdaugherty** [comment] 2020-08-31 15:46
Thanks! This is a duplicate of #562.

**Closed by jtdaugherty** 2020-08-31 15:46 UTC
