### ISSUE TITLE
matternhorn quit with openBinaryFile: invalid argument (invalid character)

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#718] opened 2021-06-18 00:02 UTC
Hello, I tried to use the 'o' keybinding on an image from a co-worker and got a crash:

```
matterhorn (edge) 50200.13.0 from Alan Pope 🐧 (popey) refreshed
⏚ [sarnold:~] 26s $ matterhorn
matterhorn: /home/sarnold/snap/matterhorn/149/.cache/matterhorn/files/c1qmzufrajngpgxk5inzwbtojy/Zdjcia 298.JPG: openBinaryFile: invalid argument (invalid character)
⏚ [sarnold:~] 3d5h39m14s 1 $ 

```

Thanks

**Comment by setharnold** [comment] 2021-06-18 00:03
Once I've restarted, the message looks like:

```
[attached: `Zdjęcia 298.JPG`]
```

Thanks

**Comment by jtdaugherty** [comment] 2021-06-18 00:05
Thank you for the report! This is a duplicate of #684.

**Comment by setharnold** [comment] 2021-06-18 00:05
Woot, thanks!

**Closed by jtdaugherty** 2021-06-18 00:05 UTC
