### ISSUE TITLE
Support for using chat behind http proxy

### ISSUE THREAD

**Issue by tanandy** [matterhorn-chat/matterhorn#302] opened 2017-08-09 07:50 UTC

**Comment by dagit** [comment] 2017-08-09 08:34
Could you say a bit more about what you want to do. Specifically, I've not use HTTP proxies in the past. Could you point me towards a test case or something like that so I know how to tell when I've got it working?

Thanks.

**Comment by tanandy** [comment] 2017-08-09 08:42
Hum, i want to use matterhorn chat to connect to mattermost but i only can access mattermost through http proxy,  

so as i did with mattermost client binary with settings ./mattermost --proxy-server=http://proxyhost:port

i would really appreciate if i could do the same or even specify it in config.ini as properties

**Comment by tanandy** [comment] 2017-08-09 09:00
The test case would be to block direct connection to mattermost port (ex:443) (firewall etc...)  and set up an http proxy like squid who has access to mattermost, so you can bypass the firewall rule using the squid proxy

**Comment by kquick** [comment] 2017-08-09 16:21
There are many ways to configure squid proxying.  To make sure we resolve the problem you are having, could you provide a simple example of a localhost squid proxy configuration that demonstrates the problem and indicate what does or doesn't seem to work when you run matterhorn against the proxy?

**Comment by jtdaugherty** [comment] 2017-09-07 01:45
I'm closing this due to lack of detail and inactivity. @tanandy, please re-open once you can provide the detail @kquick asked about. Thanks!

**Comment by prabhu-madanagopal** [comment] 2017-09-09 00:25
This is still an issue. matterhorn doesn't seem to honor any of following command line environment variables:
ALL_PROXY
HTTP_PROXY
HTTPS_PROXY
Other command line tools that support all or some of above env are brew, elinks, googler...
When network settings use proxy, matterhorn login error is could not connect to server.

**Comment by jtdaugherty** [comment] 2017-09-09 15:17
@prabhu-madanagopal - your comment suggests you're specifically looking for SOCKS proxy support. @tanandy - is this true for you, as well?

**Comment by jtdaugherty** [comment] 2017-09-09 16:13
I've added SOCKS proxy support in https://github.com/matterhorn-chat/mattermost-api/commit/4a204a823f21d215cf53391eef5a63af36b17972. @kquick - would you mind reviewing that patch?

**Comment by jtdaugherty** [comment] 2017-09-09 16:14
(In particular, note that this supports *only* SOCKS proxies, so proxy URIs with any scheme other than `socks4` or `socks5` will not be used.)

**Comment by prabhu-madanagopal** [comment] 2017-09-09 18:58
@jtdaugherty When can I test this?

**Comment by kquick** [comment] 2017-09-09 19:19
@jtdaugherty, that patch looks good.  

For completeness, we should probably support the `NO_PROXY` environment variable, which is a comma-separated list of hostnames that shouldn't be proxied (and allows a '*' wildcard specification).

Also of note: this doesn't support any proxy authentication.  I think that's fine for this situation, and we should just document that.

**Comment by jtdaugherty** [comment] 2017-09-09 19:24
@kquick - thanks, I'll update the patch to support `NO_PROXY`. I'll also add a comment about authentication. (The lack of support is largely a consequence of the lack of support in `connection`.)

**Comment by jtdaugherty** [comment] 2017-09-09 19:26
@prabhu-madanagopal - you can test it now:

* `$ git clone https://github.com/matterhorn-chat/matterhorn -b develop`
* `$ cd matterhorn`
* `matterhorn$ ./install.sh`
* `matterhorn$ cd deps/mattermost-api && git checkout feature/proxy-support`
* `mattermost-api$ cd - && ./install.sh`

**Comment by jtdaugherty** [comment] 2017-09-09 19:37
@kquick - new changes at https://github.com/matterhorn-chat/mattermost-api/commit/f43c0738476569c533da48cf59500ae31d354ea0 and https://github.com/matterhorn-chat/mattermost-api/commit/0c9a80e7a2df679e6794cd8fb6a7b28ffec11aa5.

**Comment by tanandy** [comment] 2017-09-09 20:27
thanks for update, seems to be the thing i asked but i dont think it is socks protocol just a simple http proxy

**Comment by prabhu-madanagopal** [comment] 2017-09-09 20:37
http proxy for me too :) the fix did not work for me. my env:
ALL_PROXY=http://proxy:8083

**Comment by jtdaugherty** [comment] 2017-09-09 20:42
I'm not sure it even makes sense to use an HTTP proxy with a service like Mattermost, unless the only reason for the proxy is to avoid blocking firewalls. Is that the case for either of you?

**Comment by tanandy** [comment] 2017-09-09 20:45
lot of companies use proxies to connect to the internet etc... , mattermost client already support simple http proxy  (ex: ./mattermost --proxy-server=http://proxyhost:port) so thats my request

**Comment by prabhu-madanagopal** [comment] 2017-09-09 20:47
yes my company uses http proxy as well to connect to internet.

**Comment by jtdaugherty** [comment] 2017-09-09 22:42
Plain proxy support is now added in https://github.com/matterhorn-chat/mattermost-api/commit/9420712da025ba352c9178ec6685106cae52fee1.

**Comment by prabhu-madanagopal** [comment] 2017-09-09 23:24
Error: HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type:72\nFrom:\theader\n\n")

I get this error using the patch and proxy env. without vpn (and proxy) it works fine.

**Comment by jtdaugherty** [comment] 2017-09-09 23:30
@prabhu-madanagopal - we'll need more information to diagnose, such as your proxy environment variables and proxy software information.

**Comment by jtdaugherty** [comment] 2017-09-09 23:46
@prabhu-madanagopal does your proxy support TLS? If so, set `HTTPS_PROXY`, not `HTTP_PROXY`, and that should work.

**Comment by jtdaugherty** [comment] 2017-09-09 23:46
If you are okay with using HTTP (not recommended), you'll need to disable HTTPS in your matterhorn configuration.

**Comment by prabhu-madanagopal** [comment] 2017-09-10 00:02
Setting only HTTPS_PROXY did not work.
my env:
HTTP_PROXY=http://proxy:8083
proxy server is Blue Coat web gateway http cache server. It is http not https
mattermost server is https not http.
I tried unsafeUseUnauthenticatedConnection = False, still same error invalid header type:72.
Is this setting a problem?

**Comment by jtdaugherty** [comment] 2017-09-10 00:04
Thanks for the info. The problem is that `matterhorn` is still attempting to treat the proxy connection as an SSL connection even when it is not, hence the parsing error. We'll have to see what more needs to be done and whether it's feasible to support non-socks proxies.

**Comment by jtdaugherty** [comment] 2017-09-10 00:06
(Specifically, `matterhorn`'s connection library is not issuing a `CONNECT` command to the proxy.)

**Comment by prabhu-madanagopal** [comment] 2017-09-10 00:45
https://hackage.haskell.org/package/http-proxy will this help for http proxy instead of https://hackage.haskell.org/package/connection I don't know if this is a simple change or even compatible. Thanks

**Comment by jtdaugherty** [comment] 2017-09-10 01:36
That library's dependency load is undesirable. We will definitely look for alternatives. Thanks!

**Comment by tanandy** [comment] 2017-09-10 09:45
Here an exemple how To set a basic squid for basic http proxying https://www.linode.com/docs/networking/squid/squid-http-proxy-ubuntu-12-04

Luckily we use simple http proxy with no authent . I Will try your patch

**Comment by tanandy** [comment] 2017-09-20 13:05
tried the patch:

`git clone https://github.com/matterhorn-chat/matterhorn -b develop OK
 cd matterhorn
./install.sh
The package location 'deps/aspell-pipe' does not exist.
`

on master branch ./install.sh works better

**Comment by jtdaugherty** [comment] 2017-09-20 17:25
@tanandy, please do the following:

 * remove `deps/`
 * switch to matterhorn's `develop` branch
 * `git pull` in `matterhorn`
 * switch to the `feature/socks-proxy` branch in `deps/mattermos-api`
 * Run matterhorn's `install.sh`

**Comment by tanandy** [comment] 2017-09-21 09:38
thx tried it on my older installation:
`matterhorn $ ./install.sh
current branch feature/socks-proxy is up to date 
current branch  develop is up to date 
current branch master is up to date 
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: binary-0.7.5.0/installed-578... (dependency of text-1.2.2.2)
next goal: matterhorn (user goal)
rejecting: matterhorn-40000.1.0 (conflict: binary =>
containers==0.5.6.2/installed-e59..., matterhorn => containers>=0.5.7 && <0.6)
rejecting: matterhorn-40000.0.2, matterhorn-40000.0.1, matterhorn-40000.0.0,
matterhorn-31000.0.0, matterhorn-30802.1.0 (constraint from user target
requires ==40000.1.0)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: matterhorn, mattermost-api
`
tried on a fresh install:
`git clone https://github.com/matterhorn-chat/matterhorn
cd matterhorn
./install.sh
git checkout develop
git pull
cd deps/mattermost-api
git checkout feature/socks-proxy
cd matterhorn
./install.sh
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: binary-0.7.5.0/installed-578... (dependency of text-1.2.2.2)
next goal: matterhorn (user goal)
rejecting: matterhorn-40000.1.0 (conflict: binary =>
containers==0.5.6.2/installed-e59..., matterhorn => containers>=0.5.7 && <0.6)
rejecting: matterhorn-40000.0.2, matterhorn-40000.0.1, matterhorn-40000.0.0,
matterhorn-31000.0.0, matterhorn-30802.1.0 (constraint from user target
requires ==40000.1.0)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: matterhorn, mattermost-api
`

**Comment by jtdaugherty** [comment] 2017-09-21 21:59
Please execute these steps only, with fresh clone of the repository:
* `git clone https://github.com/matterhorn-chat/matterhorn -b develop`
* `cd matterhorn/deps/mattermost-api`
* `git checkout feature/socks-proxy`
* `cd ..`
* `./install.sh`

**Comment by tanandy** [comment] 2017-09-22 08:50
hum, i dont understand since i dont see deps in develop branch (https://github.com/matterhorn-chat/matterhorn/tree/develop)

so change directory cant work

**Comment by prabhu-madanagopal** [comment] 2017-09-22 15:18
I installed cabal (using Google) to resolve cabal dependency and build successfully.

**Comment by jtdaugherty** [comment] 2017-09-22 15:22
@tanandy - sorry, here:
* `git clone https://github.com/matterhorn-chat/matterhorn -b develop`
* `cd matterhorn`
* `./install.sh` (this is only important for creating `deps`; you can kill after that.)
* `cd deps/mattermost-api`
* `git checkout feature/socks-proxy`
* `cd ..`
* `./install.sh`

**Comment by johanfagerstroem** [comment] 2018-08-14 08:30
Are there any plans to rebase the socks-feature to the latest release, or merge it to master?

**Comment by jtdaugherty** [comment] 2018-08-14 15:12
@johanfagerstroem All of the commits mentioned in the discussion above have already been merged and released in prior versions of Matterhorn.

**Comment by johanfagerstroem** [comment] 2018-08-14 16:58
Maybe I am forseeing something when i interpret the git logs. According to matterhorn.cabal and "matterhorn--version", Matterhorn 40901.0.0 uses 40900.1.0 of the mattermost-api. Checking out 40900.1.0 of the API and running "grep -ri proxy" gives nothing.

And also, lots of kudos. I really love the app.

**Comment by jtdaugherty** [comment] 2018-08-14 18:11
@johanfagerstroem thanks for digging; I was wrong and I forgot that we didn't actually merge that. (We planned on it and I even updated the `README` but later backed out the change.) We certainly *could* merge it, but this ticket wasn't providing enough clarity on what, exactly, was needed. Some of the comments alluded to problems but our requests to get more specific about what wasn't working didn't really get much of a response.

Here is the status as I understand it: the `mattermost-api` branch supports SOCKS proxies (versions 4 and 5) as well as non-SOCKS proxies. The challenge is that there are many potential proxy configurations and we need someone to volunteer a specific one and test with it. Once that testing is done, we can write documentation about what (not) to expect.

**Comment by johanfagerstroem** [comment] 2018-08-14 18:58
@jtdaugherty I volunteer. I work with protocol proxies and socket-level programming on a daily basis, so I'd be happy to do some testing and evaluation, and possibly some pull requests. However, I'm not a haskell developer so dont expect to much of the latter one. Could you rebase the feature-branch? It is 76 commits behind master.

**Comment by jtdaugherty** [comment] 2018-08-14 19:47
The `feature/socks-proxy` branch of `mattermost-api` has been updated. Assuming you have a Haskell build toolchain installed (GHC and `cabal`), to build Matterhorn with this version of `mattermost-api`:
* Git clone Matterhorn on the `develop` branch.
* Edit `install.sh` and change `clone_or_update_repo "${branch}" "$MATTERMOST_API_REPO" "$MATTERMOST_API_DIR"` to `clone_or_update_repo "feature/socks-proxy" "$MATTERMOST_API_REPO" "$MATTERMOST_API_DIR"`.
* Run `install.sh`. This will fetch the dependency sources and build `matterhorn`. Note that despite the script's name, it will only build, not install, Matterhorn.
* Run `run.sh` to run Matterhorn.

**Comment by jtdaugherty** [comment] 2018-08-14 19:47
And thanks for offering to test!

**Comment by jtdaugherty** [comment] 2019-01-10 17:41
@johanfagerstroem this ticket has been quiet for a while. Are you still interested in doing any testing on this?

**Comment by johanfagerstroem** [comment] 2019-01-14 17:13
Hi again @jtdaugherty! In the beginning, i ran out of spare time for this, and then my team decided to replace Mattermost with another solution. If still necessary, i can do some testing. Could you provide me with a build?

**Comment by johanfagerstroem** [comment] 2019-01-23 14:37
Sorry, i forgot to mention that i run Linux (both Ubuntu and Debian is fine). I have tried to build it my self but the instructions above seem outdated. At least the install.sh script is gone.

**Comment by jtdaugherty** [comment] 2019-01-23 18:02
Oh, I did indeed forget to ask which platform you're on. Try this one:

https://owncloud.galois.com/index.php/s/wKKwbqLfH7NA7Xv

**Comment by johanfagerstroem** [comment] 2019-02-07 18:37
@jtdaugherty that build doesnt seem to honor the proxy environment variables at all. I will look into making a build myself. Do you have any instructions?

**Comment by jtdaugherty** [comment] 2019-02-07 18:40
@johanfagerstroem it depends on what you need instructions for. Our `build.sh` script performs the build but assumes you already have `ghc` (I recommend version 8.4.1) and `cabal-install` (I recommend version `2.4.1.0`) installed. If you need instructions for installing those, let me know. Otherwise doing a build is done with
```
$ git checkout <branch>
$ git submodule update --init
$ ./build.sh
```

**Comment by jtdaugherty** [comment] 2019-02-07 18:41
If you are on a supported platform then you can run `setup/setup_linux.sh` to set up a Haskell toolchain on your system.

**Comment by johanfagerstroem** [comment] 2019-02-12 20:05
I've done some testing now and deeper code reviewing in combination with the comments above in this thread, and my opinion is that you should revert the changes in https://github.com/matterhorn-chat/mattermost-api/commit/9420712da025ba352c9178ec6685106cae52fee1, and only keep SOCKS proxy support.

Having HTTP proxy support without CONNECT is just confusing, since it only works for servers running plain HTTP. I assume no one as of 2019 run their mattermost servers on HTTP (if so, internally, but then there would be no need for a proxy).

The only thing I have found not working are wildcards on NO_PROXY. I have set NO_PROXY="*.mypersonaldomain.com" and have my mattermost hosted on mattermost.mypersonaldomain.com. On a machine that has *no* internet connection without proxy, it still connects, which is undesired, since *.mypersonaldomain.com should not be proxied. See http://www.gnu.org/software/wget/manual/html_node/Proxies.html for reference.

**Comment by jtdaugherty** [comment] 2019-02-12 20:07
Thank you for reviewing, @johanfagerstroem!

**Comment by johanfagerstroem** [comment] 2019-02-12 20:08
No worries! With the above two issues fixed, I think the feature/support is just perfect if stated explicitly in the docs that the application *only* supports SOCKS.

**Comment by jtdaugherty** [comment] 2019-02-12 20:44
Thanks, that helps. One of the questions raised in this ticket was whether SOCKS support was enough to address the needs of the others involved here, but since there hasn't been any engagement after attempts to get input, I'm happy to declare this done enough for now with just SOCKS support.

**Comment by jtdaugherty** [comment] 2019-05-23 21:24
The fixes described above have been applied in the `develop` branch. Thanks, everyone!

**Closed by jtdaugherty** 2019-05-23 21:24 UTC
Labels: enhancement, investigate
