### ISSUE TITLE
Commands to change status are not documented and do not complete

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#595] opened 2020-04-09 23:37 UTC
Commands like /away, /dnd, /offline and /online work but are not documented AFAICS and they do not appear in the / command completion UI.  I only found out about them from a coworker and had previously thought Matterhorn had no way of controlling status.

**Comment by jtdaugherty** [comment] 2020-04-10 20:49
Thanks for the report! This is a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/476 so I'm going to close in favor of that other one.

**Closed by jtdaugherty** 2020-04-10 20:49 UTC
