### ISSUE TITLE
JSON Decode Exception

### ISSUE THREAD

**Issue by acw** [matterhorn-chat/matterhorn#299] opened 2017-07-27 23:10 UTC
Unfortunately I was in another tmux window when this occurred, so I don't know the exact trigger:

```
matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.event: Unknown websocket message: \"emoji_added\"", jsonDecodeExceptionJSON = "{\"event\":\"emoji_added\",
\"data\":{\"emoji\":\"{\\\"id\\\":\\\"ax1zs7hm9fympeqfb6fnps8oco\\\",\\\"create_at\\\":1501194191402,\\\"update_at\\\":1501194191402,\\\"delete_at\\\":0,\\\"creator_id\\\":\\\"
bjgq7fkin7dk9qomzi7nwinpfe\\\",\\\"name\\\":\\\"pillspin\\\"}\"},\"broadcast\":{\"omit_users\":null,\"user_id\":\"\",\"channel_id\":\"\",\"team_id\":\"\"},\"seq\":12}"}
```

I'm on commit `45d9516` in `matterhorn`, and `1974a125` in `matterhorn-api`.

**Comment by kquick** [comment] 2017-07-27 23:14
Duplicate of issue #296, but thank you for the report!

**Closed by kquick** 2017-07-27 23:14 UTC
