### ISSUE TITLE
Matterhorn doesn't mark messages as read if the said message has been read from another client.

### ISSUE THREAD

**Issue by krish8664** [matterhorn-chat/matterhorn#342] opened 2017-12-13 05:07 UTC
Hi,

I have 2 mattermost clients (mobile + matterhorn)/(mobile + native macOS + matterhorn) running simultaneously. When I read a message on matterhorn it gets marked as read on the other clients but if I've read it on some other client, matterhorn doesn't mark them as read.

I would expect matterhorn to mark these messages as read, if I've read them on another client.

**Comment by jtdaugherty** [comment] 2017-12-13 05:21
Thanks for the report! We'll look into it.

**Comment by jtdaugherty** [comment] 2017-12-13 06:37
Reading your report again, I guess it does; otherwise it wouldn't be working for any clients.

**Comment by jtdaugherty** [comment] 2017-12-13 06:38
We'll need to enable this on our development server and figure out what's going on.

**Comment by krish8664** [comment] 2017-12-14 07:55
@jtdaugherty Thank you for looking into it.

**Comment by jtdaugherty** [comment] 2018-01-02 19:02
Okay, the problem is that we looked in the wrong part of the websocket event for the channel ID that we needed to use to trigger the right behavior. We have some more work that needs to be finalized before this fix can be safely added, however. Once we're ready, we'll implement this fix. It will be available in one of the next two releases.
```diff
diff --git a/src/Events.hs b/src/Events.hs
index de8a59e..21994c1 100644
--- a/src/Events.hs
+++ b/src/Events.hs
@@ -190,7 +190,7 @@ handleWSEvent we = do
             | otherwise -> return ()

         WMChannelViewed
-            | Just cId <- webChannelId $ weBroadcast we -> refreshChannelById False cId
+            | Just cId <- wepChannelId $ weData we -> refreshChannelById False cId
             | otherwise -> return ()

         WMChannelUpdated
```

**Comment by kquick** [comment] 2018-01-16 22:10
This issue is fixed on the `develop` branch.

**Closed** 2018-01-17 06:02 UTC
Labels: bug, feature-parity

**Comment by krish8664** [comment] 2018-01-18 06:03
Awesome! Thanks guys!
