### ISSUE TITLE
Typing with user-typing notifications causes websocket timeout

### ISSUE THREAD

**Issue by immindich** [matterhorn-chat/matterhorn#529] opened 2019-09-16 18:23 UTC
Whenever I leave a channel using the `leave` command, the channel stays open in the client until I restart it. The client will then briefly disconnect and, upon reconnecting, give the following error message, presumably because it is trying to fetch messages from a channel that I am no longer a member of.

> No channel member found for that user ID and channel ID

I can reproduce this pretty consistently since it happens every time I try to leave a channel.

**Comment by jtdaugherty** [comment] 2019-09-16 18:41
For what kind(s) of channels does this occur for you? Public, private, private group, DM, etc.?

**Comment by jtdaugherty** [comment] 2019-09-16 18:47
I believe that error message arises from a call to `mmGetChannelMember`, which requests membership metadata for a particular user/channel combination.

**Comment by jtdaugherty** [comment] 2019-09-16 18:49
Also, can you turn on logging, try this, and provide the log?

**Comment by immindich** [comment] 2019-09-16 22:36
Here are the [logs](https://github.com/matterhorn-chat/matterhorn/files/3618399/log.txt) from when I try to leave a public channel.

I can also confirm that this issue affects private channels, but without the error message. Instead I get a message saying that I have archived the channel. This may be related to the fact that I was testing with a private channel that I had created.

This issue does not apply to DM channels, since they do not support the `/leave` command.

**Comment by jtdaugherty** [comment] 2019-09-16 22:45
Thanks! Looking at the log, it's very curious that there is the `DELETE` request which "leaves" the channel, followed ten seconds later by a websocket timeout exception. That's interesting because the way Matterhorn finds out you left a channel is by getting a websocket event saying so; if for some reason we aren't getting that in this case, it might explain the misbehavior.

Can you please add some logging to `Events.handleWSEvent` as follows:
```haskell
handleWSEvent :: WebsocketEvent -> MH ()
handleWSEvent we = do
    mhLog LogGeneral $ T.pack $ show we
```
Then try this again, and share the log here.

**Comment by immindich** [comment] 2019-09-16 22:57
[Updated logs](https://github.com/matterhorn-chat/matterhorn/files/3618514/log.txt)

**Comment by jtdaugherty** [comment] 2019-09-16 23:02
Interesting. The log output in your most recent update confirms that we are indeed missing the websocket event that Matterhorn needs to remove you from the channel in the UI.

Would you be willing to test again, except this time `tail -f` the log in a separate window, wait until *after* the line with the exception appears,
```
... [LogWebsocket] [*] Websocket timeout exception: MMWebSocketTimeoutException
```
and then try `/leave` at that point.

**Comment by immindich** [comment] 2019-09-16 23:15
It seems like the websocket timeout is somehow connected to sending typing notifications to the server. I have `showTypingIndicator` turned on in my config, and whenever I type something I consistently get something like:

    [2019-09-16 23:08:31.319137 UTC] [LogAPI] [*] Function: websocket, event: WebSocketRequest (Object (fromList [("data",Object (fromList [("parent_id",String ""),("channel_id",String "wxxjchr4dj8ktkdub1od8up17a")])),("action",String "user_typing"),("seq",Number 1.0)]))
    [2019-09-16 23:08:35.376062 UTC] [LogAPI] [*] Function: websocket, event: WebSocketPing
    [2019-09-16 23:08:43.382153 UTC] [LogWebsocket] [*] Websocket timeout exception: MMWebSocketTimeoutException

If I type `/leave`, wait until the client reconnects, and then press enter, then it closes the channel correctly.

**Comment by jtdaugherty** [comment] 2019-09-16 23:18
So does this behavior persist if you turn `showTypingIndicator` off?

**Comment by immindich** [comment] 2019-09-16 23:20
Everything seems to work correctly when I turn it off.

**Comment by jtdaugherty** [comment] 2019-09-16 23:21
Okay, that's a great discovery. Thank you for testing!

**Comment by jtdaugherty** [comment] 2019-09-16 23:22
(It also explains why I couldn't reproduce the problem; I don't have that setting enabled.)

**Comment by jtdaugherty** [comment] 2019-09-16 23:26
I was able to reproduce the websocket timeout just by enabling the typing indicator.

**Comment by jtdaugherty** [comment] 2019-09-16 23:27
So, steps to reproduce now:
* Set `showTypingIndicator` to `True` in the config.
* Go to any channel.
* Type a single character.

Behavior:
* Websocket times out.

**Comment by jtdaugherty** [comment] 2019-09-16 23:29
I've also reproduced this on `matterhorn-dev.galois.com`.

**Comment by jtdaugherty** [comment] 2019-09-16 23:31
It also appears that our websocket message is well-formed, at least according to
https://api.mattermost.com/#tag/WebSocket

**Comment by jtdaugherty** [comment] 2019-09-17 21:01
I've found the bug; the issue is that the websocket response to the `user_typing` event is not even parsable by the `mattermost-api` package, and never has been. But we didn't know that because of [this change](https://github.com/matterhorn-chat/mattermost-api/commit/c9074d49fcf257be697037d89dae408082f1f8e3) that I made two years ago in an effort to be more specific about which exceptions we caught. The consequence of that is that we failed to even catch the *JSON* parse failure that was happening, and that was killing one of the websocket threads in this issue here.

How this feature ever worked is a mystery, but I suspect that at some point we were silently ignoring the response parse failures rather than killing the thread the way the current code behaves.

So the fix is probably to augment the API and JSON decoder for `WebsocketEvent` type in `mattermost-api` so that success responses from actions like `user_typing` can be decoded. In addition, the exception handling above needs to be reverted to catch `SomeException`. That will ensure that any exceptions are propagated all the way to the application and reported in the message area as errors.

**Comment by EugenMayer** [comment] 2019-10-28 07:35
Same here, i was not aware of the issue just happened to have long timeouts to see the actual message i just wrote and could track it down to this. AFAICS there is nothing else needed to reproduce, this bug is about to get fixed?

**Comment by jtdaugherty** [comment] 2019-10-28 16:48
@EugenMayer that's right; the bug has been characterized but we haven't had time to fix it yet. It will be fixed in the next release, though.

**Comment by jtdaugherty** [comment] 2020-02-03 19:36
This is now fixed in `develop` and will go out in the next release.

**Closed by jtdaugherty** 2020-02-03 19:36 UTC
Labels: bug
