### ISSUE TITLE
Trouble opening URL in message from slash command

### ISSUE THREAD

**Issue by davidlind** [matterhorn-chat/matterhorn#770] opened 2022-06-29 10:16 UTC
Hi!
When using a certain custom slash command a bot responds with an URL that is clickable in Mattermost, but in Matterhorn no link is clickable. Here are a couple of screenshots:

In Mattermost:
![bbb_mattermost](https://user-images.githubusercontent.com/1058316/176412734-e897d79d-2148-416d-a103-5e1058b47a86.png)

In Matterhorn:
![bbb_matterhorn](https://user-images.githubusercontent.com/1058316/176412784-582c84f0-575e-421c-9d93-e637cad93f7a.png)

Any idea about why this isn't working?

All the best,

David

**Comment by jtdaugherty** [comment] 2022-06-29 15:10
Hi @davidlind. In general, Matterhorn only knows about clickable links that come in Markdown content. The custom slash command in use here is generating a message that is not a Markdown message, so Matterhorn doesn't see any links.

This is another case of https://github.com/matterhorn-chat/matterhorn/issues/630. Looking at the source for the BigBlueButton plugin, the plugin uses Slack attachment structures in the message to embed the UI elements that you are seeing, and the web client knows how to present those. Matterhorn doesn't know about those, and I haven't done research to know whether Matterhorn can support them fully because I don't know how many assumptions that format makes about the presence of a user agent with HTML rendering and fully general mouse support.

Since this is effectively a duplicate of that older issue, I'm going to close it. But that is the reason why this isn't working: the bot uses Slack actions to drive its UI, not Markdown, and Matterhorn doesn't support those yet. Sorry!

**Closed by jtdaugherty** 2022-06-29 15:10 UTC
