### ISSUE TITLE
Unexpected reponse (4,2,9)

### ISSUE THREAD

**Issue by morsedl** [matterhorn-chat/matterhorn#561] opened 2020-02-11 10:18 UTC
│          Please report this error at                             
                    │          https://github.com/matterhorn-chat/matterhorn/issues    
                    │[11:16]   An unexpected error has occurred! The exception         
                    │          encountered was:                                        
                    │          HTTPResponseException "Server returned unexpected       
                    │          (4,2,9) response"                                       
                    │          Please report this error at                             
                    │          https://github.com/matterhorn-chat/matterhorn/issues

**Comment by jtdaugherty** [comment] 2020-02-11 15:32
Thanks for the report! This is a duplicate of #504.

**Closed by jtdaugherty** 2020-02-11 15:32 UTC
