### ISSUE TITLE
Issues sending attachments

### ISSUE THREAD

**Issue by THinnerichs** [matterhorn-chat/matterhorn#773] opened 2022-07-13 10:40 UTC
Dear Matterhorn team,
I couldn't find anything in the manuals and docs this time, too, so any information is highly welcome:
While using Matterhorn, I am struggling to send attachments. I am able to select the attachment and it displays `1 attachment ...` above the message box. However, it does not send the attachment, but just the text when pressing Enter/return afterwards. Am I missing some configuration again? 

Thank you very much for your help!

**Comment by jtdaugherty** [comment] 2022-07-13 14:04
Hi @THinnerichs - which version of Matterhorn are you using? And how large is the attachment you are trying to send?

**Comment by THinnerichs** [comment] 2022-07-14 05:55
Hey @jtdaugherty,
thank you very much for the quick response! Attachments tried were ranging from 1kb to 2mb, nothing fancy. 
Matterhorn version:
```matterhorn 50200.17.0 (develop@8661bff)
 using mattermost-api 50200.13.0 (HEAD@273adac)```

**Comment by jtdaugherty** [comment] 2022-07-14 15:27
@THinnerichs when you attempt to send the message, does it contain any text at all? Or just the attachment?

**Comment by THinnerichs** [comment] 2022-07-21 12:45
Sorry, for the delayed response, @jtdaugherty . I tried a reinstallation, went through my configs, and re-skimmed the docs in the mean time. Nothing new.

I tried both, but both fail. If I send attachment + text, only the text is sent.

**Comment by jtdaugherty** [comment] 2022-07-21 14:07
Hm, that's really strange. Can you tell me which version of Mattermost the server is running? (This can be obtained from the official web client for that server.)

**Comment by jtdaugherty** [comment] 2022-10-03 20:50
@THinnerichs it's been a while and I wanted to follow up again. Any chance you could find out what version of the server you were using when this happened? If we can't get any clues about this, I'd like to close it and re-open later if it happens again. Thanks!

**Comment by jtdaugherty** [comment] 2022-10-04 17:52
No problem at all. Thanks for letting me know. I asked about the server version because it helps us track down whether Matterhorn has an incompatibility that we don't know about, not because I'm eager to blame the server. :) If you could get the versions of the other servers where you experienced this, that would also be very helpful.

**Comment by nlhomme** [comment] 2023-03-28 08:49
Hello @jtdaugherty,

I wanted to let you know that I encounter the same issue with mattermost server 7.9.1 and matterhorn 50200.17.0 on macOS 13.3 :)

Regards

**Comment by jtdaugherty** [comment] 2023-04-14 03:11
@nlhomme I know it has been a while, but I'm wondering if you could provide more information. I have not been able to reproduce this problem. Do you get any error messages when the attachment fails to send? Or do you just see a text-only post with no attachments?

A request for you: could you run matterhorn with `-l log.txt`, send a message with an attachment, and then post the log file here? That might help us spot what is going on under the hood.

**Comment by nlhomme** [comment] 2023-04-17 13:42
Hello,

Here is the log file:
[log.txt](https://github.com/matterhorn-chat/matterhorn/files/11250774/log.txt)

Here is the file I tried to send:
![bob-kelso](https://user-images.githubusercontent.com/9362475/232501730-9742aaaf-d022-47b3-8033-fe90403e61f8.jpg)

The file is located at `/Users/nilho/Pictures/Memes/bob-kelso.jpg`:
```
ls -lh /Users/nilho/Pictures/Memes/bob-kelso.jpg
-rwxrw-r--@ 1 nilho  staff   8,6K 15 sep  2020 /Users/nilho/Pictures/Memes/bob-kelso.jpg
```

**Comment by jtdaugherty** [comment] 2023-04-17 17:03
Thanks, @nlhomme. I looked at the log file you posted, but judging by that, no messages were posted at all in the session that generated that log file. For each posted message we should see a line containing this:
```
[LogAPI] [*] Function: submitRequest, event: HttpRequest POST "/posts" Nothing
```

**Comment by nlhomme** [comment] 2023-04-19 09:07
I swear I did the actions :p

**Comment by jtdaugherty** [comment] 2023-04-19 09:13
I don't mean to say that you didn't - only that the log doesn't provide the evidence. I was really confused by that but wasn't sure what to do. You could attempt another round of logging while posting an attachment and check the log for the lines I mentioned, I suppose.

**Comment by jtdaugherty** [comment] 2024-11-16 23:24
Thanks @Spreadcat and others - this is now fixed on `develop` and will go out in the next release.

**Closed by jtdaugherty** 2024-11-16 23:24 UTC
