### ISSUE TITLE
Copied text has no line endings

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#636] opened 2020-07-06 18:34 UTC
When filing https://github.com/matterhorn-chat/matterhorn/issues/635 I found that output that spanned several lines in my terminal was pasted into a single line when selected. For example, the following is supposed to be ten lines long:

```
                    │──────────────────────────────────────────────────────────────────────2020-07-06──────────────────────────────────────────────────────────────────────                     │[17:37:12] Cannot send messages while disconnected.                                                                                                                        │[17:37:12] Disconnected. Will refresh when connected.                                                                                                                      │[18:25:28]   Unknown help topic: reconnect. Available topics are:                                                                                                          │             • main                                                                                                                                                        │             • scripts                                                                                                                                                     │             • themes                                                                                                                                                      │             • keybindings                                                                                                                                                 │             • syntax                                                                                                                                                      │[18:25:28] Disconnected. Will refresh when connecte
```

Not having line endings at the end of lines makes pastebin sites less useful, and complicates filing github issues about the display.

Thanks

**Comment by jtdaugherty** [comment] 2020-07-06 18:37
Is your objective to copy the contents of a message to your clipboard in and to preserve it verbatim?

**Comment by jtdaugherty** [comment] 2020-07-06 19:02
A couple of things to note:
* Assuming you want to copy verbatim message text as I asked above, then the best way to do that is to select the desired message with `C-s` and then press `y` or `Y` to yank either the code blocks (`y`) or the entire message text (`Y`). That feature uses the system clipboard to copy the text verbatim. An advantage of this approach, beyond getting line endings consistently, is that it doesn't result in you copying Matterhorn UI decorations.
* This seems to be a matter of terminal emulator copy behavior, since for me on iTerm2 on macOS, copied text from Matterhorn's user interface includes line endings. Consequently this is not due to Matterhorn's behavior

**Comment by setharnold** [comment] 2020-07-06 19:34
There's two reasons why I've selected contents via mouse so far:

The first is to try to show a series of messages from matterhorn; probably the log would do a better job there anyway.

The second is to share a portion of a conversation in an email, bug report, etc. In this case, a single message isn't very useful for me: I want the person who is speaking to be identified, and I want `HH:MM:SS` timestamps, so readers can better understand the flow of responses. (Thanks for `timeFormat: %T` :)

I'm using `urxvt`; I wonder where this difference is coming from?

Thanks

**Comment by jtdaugherty** [comment] 2020-07-06 19:42
> probably the log would do a better job there anyway

Unfortunately not; user messages do not appear in the Matterhorn log.

**Comment by jtdaugherty** [comment] 2020-07-06 19:44
> Unfortunately not; user messages do not appear in the Matterhorn log.

For what it's worth, we also have https://github.com/matterhorn-chat/matterhorn/issues/583.

**Comment by jtdaugherty** [comment] 2020-07-06 20:01
Another thing that might help you in your desire to copy only what you want is `F2` (alternative: `/toggle-channel-list`).

**Comment by jtdaugherty** [comment] 2020-07-06 23:10
On macOS, I installed XQuartz and `rvxt-unicode` (`urxvt`) to see if I could reproduce this. I ran Matterhorn and double-clicked on some text, dragged to select multiple lines, and clicked Copy in XQuartz's `Edit` menu to get it into the macOS clipboard. Then I pasted that into a `vim` editor and the paste had line endings built into it. So I wasn't able to reproduce the issue you ran into. For what it's worth, my build's `urxvt --version` says `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`.

**Comment by jtdaugherty** [comment] 2020-07-11 22:27
@setharnold did you find out any more information that might shed light on what is going on for your copy/pastes?

**Comment by setharnold** [comment] 2020-07-13 23:29
Sorry, no progress on this on my end. Thanks.

**Comment by jtdaugherty** [comment] 2020-07-23 18:10
@setharnold since I can't reproduce this, I'm going to close it - but if you get more information and want to reopen it, please do!

**Closed by jtdaugherty** 2020-07-23 18:10 UTC
