### ISSUE TITLE
unexpected /root/.cabal/ file access when running as a user

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#768] opened 2022-06-09 01:57 UTC
Hello, I'm running @3v1n0 's matterhorn snap and found a surprising file access when inspecting what it does with the bpfcc `opensnoop` command (`opensnoop-bpfcc` on Ubuntu 20.04 LTS):

```
...
2803483 matterhorn:w       -1   2 /home/sarnold/snap/matterhorn/331/.config/matterhorn/syntax
2803483 matterhorn:w       17   0 /snap/matterhorn/331/app/syntax
2803483 matterhorn         18   0 /home/sarnold/snap/matterhorn/331/.config/matterhorn/last_run_state_sqmc4sz45prypmkfctwynm5yjr.json
2803483 matterhorn:w       17   0 /snap/matterhorn/331/app/syntax/abc.xml
2803483 matterhorn:w       17   0 /snap/matterhorn/331/app/syntax/actionscript.xml
...
2803483 matterhorn:w       18   0 /snap/matterhorn/331/app/syntax/yaml.xml
2803483 matterhorn:w       18   0 /snap/matterhorn/331/app/syntax/zsh.xml
2803483 matterhorn:w       -1   2 /root/.cabal/share/x86_64-linux-ghc-8.6.5/matterhorn-50200.16.0/syntax
2803483 matterhorn:w       18   0 /dev/random
2803483 matterhorn:w       18   0 /dev/urandom
...
```

I'm specifically surprised about the access to `/root/.cabal/...`.

This might be an artifact of the snap packaging, or it might be an artifact of the matterhorn build system, I have no idea at the moment.

Thanks

**Comment by jtdaugherty** [comment] 2022-06-09 02:29
This would seem to be an artifact of how the snap package is build. Is there a repo on which this issue could be filed instead?

**Comment by setharnold** [comment] 2022-06-10 02:36
On Wed, Jun 08, 2022 at 07:29:27PM -0700, Jonathan Daugherty wrote:
> This would seem to be an artifact of how the snap package is built. Is
> there a repo on which this issue could be filed instead?

Thanks for looking into it. Unfortunately, Trevinho's repo doesn't have
Issues because it's a fork of someone else's repo:

https://github.com/3v1n0/matterhorn-snap

Given that it is now out of date vs what's in the snapstore:
https://snapcraft.io/matterhorn
I'm not sure where the actual thing is maintained.

Feel free to close this if you'd rather keep the place neat and tidy.
Thanks for investigating. :)

**Comment by jtdaugherty** [comment] 2022-06-10 02:38
Okay, thanks. I'll close it, but it might be helpful if @3v1n0 can set up some place for these issues to be reported. In the mean time, there's always the official binaries that you can run. 😊

**Closed by jtdaugherty** 2022-06-10 02:38 UTC

**Comment by setharnold** [comment] 2022-06-10 02:51
Yeah, and given how it complicates basically every troubleshooting step, I
wonder why I haven't switched yet every single time I ask for help. :)

**Comment by 3v1n0** [comment] 2022-06-10 13:09
> Thanks for looking into it. Unfortunately, Trevinho's repo doesn't have Issues because it's a fork of someone else's repo: https://github.com/3v1n0/matterhorn-snap Given that it is now out of date vs what's in the snapstore: https://snapcraft.io/matterhorn I'm not sure where the actual thing is maintained.

No, no that repo is updated. It's just that the package gets built automatically from build.snapcraft.io, so the snap itself doesn't need much maintenance but that's where the snap sources are picked from.

So feel free to report there, however we just build the snap using the same script that is used upstream, so the issue could be belonging to this repo as well indeed: https://github.com/3v1n0/matterhorn-snap/blob/master/snap/snapcraft.yaml#L80-L81

**Comment by jtdaugherty** [comment] 2022-06-10 14:53
@3v1n0 in this particular case I strongly suspect this is something to do with the Snap build process. The release-building script you're using doesn't use sudo (none of our scripts do) so the involvement of anything in the root home directory suggests that some part of your build process is running as root.

The specific directory being accessed in the original report is the Cabal user data directory for the Matterhorn package. That suggests that the Haskell binary is being built by `root`.

Also, for what it's worth, this is benign and not a bug or a problem to be fixed; Matterhorn tries several directories to find syntax specifications, and the user data directory for the package is just one of them. If it can't read from that path, it's harmless. It's not an indication of a problem with the build per se.

**Comment by 3v1n0** [comment] 2022-06-10 14:55
>  so the involvement of anything in the root home directory suggests that some part of your build process is running as root.

Indeed that's the case, but I feel that the binary shouldn't hardcode the $HOME path anyways, no? In the sense that even if it was built by an user I suspect that the builder home user home will still be hardcoded.

**Comment by jtdaugherty** [comment] 2022-06-10 14:57
It isn't hardcoding `$HOME`; it's hardcoding the path of the Haskell library installation path as *one* of its syntax search paths, which happens to be in `$HOME/.cabal`. In practice that search path will almost always never exist. The binary searches in that particular directory (again, as one of many) to support the Haskell library installation use case where `matterhorn` is installed by `cabal` rather than distributed by our release process.
