### ISSUE TITLE
Support different user name representations

### ISSUE THREAD

**Issue by bernerha** [matterhorn-chat/matterhorn#265] opened 2017-06-30 07:50 UTC
It would be nice to change how the name in the user list will be shown.
Change between nickname, full name or username with a command or set a default in the config.

Cheers

**Comment by jtdaugherty** [comment] 2017-06-30 18:47
What should happen if a user has no nickname?

**Comment by jtdaugherty** [comment] 2017-06-30 18:49
We have two choices: fall back to either full name or username.

**Comment by bernerha** [comment] 2017-07-03 06:55
Good question. Fall back to the username or make it configurable e.g with a list `nickname, full_name, username`.

**Comment by jtdaugherty** [comment] 2017-09-02 03:42
@kellymclaughlin - you mentioned elsewhere that you'd potentially be willing to help out with this. A while back I started looking into this request and it's quite a big change due to the pervasive use of user names in so many places. Some design questions need to be resolved before work can begin.

Some issues are documented at https://github.com/matterhorn-chat/matterhorn/wiki/User-Name-Configurability and we'll need to flesh this out more on the wiki before moving to implementation. (For our workflow, please see https://github.com/matterhorn-chat/matterhorn/blob/develop/PRACTICES.md#design.)

**Comment by kellymclaughlin** [comment] 2017-09-05 14:50
@jtdaugherty Excellent, I'll read over the wiki and put some thought into it and then go from there.

**Comment by kellymclaughlin** [comment] 2017-09-25 15:34
I've spent some time looking into this a little bit and here's a few thoughts I have:

* For most cases I think it makes sense to mirror the behavior of the mattermost desktop client when the user chooses to display nicknames. This means the User's list, the message identifiers, and the channel members list would all show nicknames.
* I'm using the mattermost Linux client as a source of comparison and it only gives one choice for falling back in cases where a user has not set a nickname. The order is *nickname -> first name last name -> username*. Personally I would prefer to fallback to the username because using the first and last names is not something I would ever prefer over just the username. We could stick with the mattermost client fallback order, but in my opinion this is a good place to diverge. For simplicity I think it would be good to keep it just to one choice for the first pass at this and take some feedback from people and see what the input is before doing anything more complicated.
* The desktop client does let you do user tab completion using the nickname, but it then substitutes in the username with the `@` and uses the username in the chat message regardless of the nickname settings. I find the behavior a little strange since the nickname is used in nearly every other context, but I can also see other alternatives being confusing and we have to account for the notification piece of it so for now mirroring that behavior seems reasonable.
* I don't have a good answer yet for the matching algorithm in the case where a nickname contains spaces so that's something I still need to investigate further.

I think the next thing I would like to do is work up a prototype branch that offers the option to enable nickname display and implements a decent portion of the changes to make it happen and then put it up so anyone interested could take it for a test drive and provide feedback. Then we can hash out any remaining questions and circle back on anything people would like to change and then work towards a PR after that. I've been using a matterhorn version where I've enabled some of the nickname display features without a config option and I'm really enjoying it so hopefully others will find it useful as well once it's all done.

Happy for any feedback, especially if anyone has observed different behaviors or options in their mattermost desktop client that might be worth noting for comparison.

**Comment by jtdaugherty** [comment] 2017-09-25 15:52
Thanks for the write-up! I'm aligned with your proposed approach and reasoning, so please proceed. I dislike the web client's handling of names (inserting one when you completed another, as you mentioned) so I'm open to being thoughtful about whether to diverge from the web client's behavior. Overall I'm skeptical about making any changes in this area, but I am very happy to try out patches and see if there is a clear path forward. Thank you for doing this work!

**Comment by kellymclaughlin** [comment] 2017-10-10 14:47
I have pushed a branch to my fork that has a first pass at this. The branch name is [feature/displayname-option](https://github.com/kellymclaughlin/matterhorn/tree/feature/displayname-option). [Here](https://github.com/matterhorn-chat/matterhorn/compare/develop...kellymclaughlin:feature/displayname-option?expand=1) is the diff with `develop`. 

It's been working well in my testing over the last few days, but happy to hear about any unexpected behavior if anyone else tries it. When enabled the option handles showing nicknames in the channel message window, the user listing, the channel members list, and uses nicknames in channel switching mode. 

There's a few things it does not handle right now:

* Nicknames do not work for tab completions and are not used for `@` mentions
* If more than one user shares the same nickname there is no means to discern the intended channel when trying to select a user channel. This could be done by additionally showing the username in parentheses beside the nickname in these situations, but it also may be a sufficiently rare case that it can be done as follow-on work if it proves to be an actual problem.
* Notifications do not work for nicknames. The mattermost desktop client has separate settings to select words that should create notifications. Perhaps it makes sense for matterhorn to also do this or we could automatically enable notifications for nicknames as well as usernames if the nickname option is enabled. The latter option is appealing because it meets my expectation of what should happen, but it would be a change from the desktop client so happy to hear what others think about it.

One note on the diff, I had sytlish-haskell set to always run on save in my editor so there's some extra formatting changes due to that, mostly in the import sections. Sorry for the extra noise, but that can always be undone prior to making a PR for this work.

**Comment by jtdaugherty** [comment] 2017-10-10 16:47
Fantastic - thanks for all this work!

> Nicknames do not work for tab completions and are not used for @ mentions

For this, ultimately I'd like the web client behavior: tab-completing nicknames leads to filling in usernames. (Not a show-stopping issue.)

Also, I just confirmed that the web client and server allow two users to have the same nickname, and that the web client provides a way to disambiguate during completion. So ultimately we'll also want something like that here. (Not a show-stopping issue.)

> If more than one user shares the same nickname there is no means to discern the intended channel when trying to select a user channel.

This is actually something I didn't notice in the web client until now, but the user list *never* shows nicknames - only full name or username. So I want to remove this feature from this branch (and that makes this problem go away). The user list should be stable.

> Notifications do not work for nicknames.

I think I'd like to avoid implicitly changing such settings; in the case of two users with the same nickname it could lead to undesirable notifications, and I'd rather let the user opt in to that.

> One note on the diff, I had sytlish-haskell set to always run on save in my editor so there's some extra formatting changes due to that, mostly in the import sections. Sorry for the extra noise, but that can always be undone prior to making a PR for this work.

Yes, please undo some of that styling to most closely match what is already in use. Also, to the extent that you can, please avoid hunks in this change set that are merely stylistic changes (such as line 217 of `Types.hs`).

Thank you!

**Comment by kellymclaughlin** [comment] 2017-10-10 17:59
> This is actually something I didn't notice in the web client until now, but the user list never shows nicknames - only full name or username. So I want to remove this feature from this branch (and that makes this problem go away). The user list should be stable.

Ok, this is really interesting. There is an option to configure this. I thought initially it was a desktop client configuration option, but looking again the option is under *System Console -> Users and Teams* so it's actually a server option. The option is called *Teammate Name Display* and establishes a preference list for display name and the value for the setting is returned as part of the response body from a v4 API request to `/config` (`/admin/config` in v3). This option appears to control all of the settings in the desktop client that I misunderstood to be client config options. So maybe instead of a new matterhorn configuration option for this behavior we also look at the server configuration and act on that. Thoughts?

**Comment by jtdaugherty** [comment] 2017-10-10 18:03
It sounds like that might mean that Matterhorn shouldn't make this configurable at all client-side, but just defer to the server. Do I have that right? If so, then yeah, that's the right thing to do.

**Comment by kellymclaughlin** [comment] 2017-10-10 18:06
> It sounds like that might mean that Matterhorn shouldn't make this configurable at all client-side, but just defer to the server. Do I have that right? If so, then yeah, that's the right thing to do.

Yeah, that's my thought as well, just read the server setting and act on that. I'll work on those adjustments, but I think most of changes thus far will still work aside from the client configuration changes.

**Comment by jtdaugherty** [comment] 2017-10-10 18:07
Okay. Thank you!

**Comment by kellymclaughlin** [comment] 2017-10-24 16:24
When I looked into grabbing the server settings for the `TeammateNameDisplay` configuration value I realized that in the v3 API the configuration information is only available from `/admin/config` which requires administrator permissions and so will not suffice for clients. In the v4 API there is a [client configuration](https://api.mattermost.com/#tag/system%2Fpaths%2F~1config~1client%2Fget) API that provides the `TeammateNameDisplay` value along with other client relevant information and does not require administrator permissions, but there does not seem to be an equivalent of this for the v3 API. 

At this point I think the completion of this change has to wait until the v4 switchover is done. In the meantime I'll keep my [branch](https://github.com/kellymclaughlin/matterhorn/tree/feature/displayname-option) up-to-date with `develop` and leave it using a client-side config option and hopefully be ready to make the final adjustments needed to submit a PR once the v4 change is done.

**Comment by jtdaugherty** [comment] 2017-10-24 16:43
@kellymclaughlin okay, thanks. If you are interested, you could add just that v4 endpoint to `mattermost-api` (and branch that, too) just to get things working. @aisamanra is working on updating `mattermost-api` to use v4 exclusively and we'll need to migrate to that by the end of this year, but any v4 endpoints that we need to introduce in the mean time can just be added and then we'll deal with the conflicts when we switch over to @aisamanra's implementation.

**Comment by jtdaugherty** [comment] 2017-11-16 18:25
@kellymclaughlin any thoughts on my comment above? The v4 switchover is still a little ways out, and I don't think this has to wait on that. We already use a mixture of v3 and v4 APIs anyway, and adding a new v4 endpoint to support this work now is okay.

**Comment by kellymclaughlin** [comment] 2017-11-16 19:36
I'd be happy to go ahead and add that v4 endpoint to `mattermost-api`. Lately I've been chipping away at the tab completion support for nicknames to try and match the MM desktop behavior in that area. I've made some progress, but it still needs more work. I think though after the tab complete stuff works the feature should be close to wrapped up and then I can update `mattermost-api` and maybe be ready for some PRs.

**Comment by jtdaugherty** [comment] 2017-11-16 19:51
Okay. Thanks!

**Comment by kellymclaughlin** [comment] 2017-12-28 21:02
@jtdaugherty As part of the original work when I thought this would be a client-side configuration I added a new field to the `Config` type and also added lenses for `Config` and plumbed in the changes to support those throughout the code. Now that matterhorn will be getting this info from the server configuration data it doesn't make sense to keep that new `Config` field. Are you interested in keeping the lenses I added for `Config` or would you prefer to have those removed as I wrap this up?

**Comment by jtdaugherty** [comment] 2017-12-28 21:35
@kellymclaughlin in general my preference is to make minimal changes, so if your changes don't end up needing the lenses, then let's leave them out. We can always put them back in later if it becomes clear that they're needed. Thanks!

**Comment by kellymclaughlin** [comment] 2017-12-28 23:39
Sounds good, thanks!

**Comment by jtdaugherty** [comment] 2018-03-02 19:11
@kellymclaughlin's pull request to support displaying and using nicknames is now merged to `develop`. There it'll undergo testing by our team and then, if all goes well, it'll go out in the next release. Thanks, everyone!

**Closed by jtdaugherty** 2018-03-02 19:11 UTC
Labels: enhancement, high-level
