### ISSUE TITLE
Open image attachments in browser instead of exposing download prompt

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/matterhorn#128] opened 2016-11-12 02:59 UTC
As of 0479194, we can open attachments, but right now opening an image doesn't let us view the image in the browser (for me, at least) and instead prompts me to download that image. It looks like Mattermost has a notion of an 'image preview' which would allow us to open a slightly different URL to view the image directly in the browser, but that the attachment points to a URL which doesn't want us to do that. In the future, it'd be nice to open image attachments in this special way to allow us to view them in the browser.

**Comment by aisamanra** [comment] 2016-11-14 19:46
It turns out that the preview URL still doesn't let us view the image in the browser: Mattermost will set the `Content-Disposition` to `attachment` for every file that you want to fetch. That means for things that can be opened in-browser that we might have to download them locally into a temp folder and then open that URL instead. This'll be annoying—in part because it'll involve sniffing the `Content-Type` to figure out which to download locally—but doable.

**Comment by jtdaugherty** [comment] 2017-02-20 20:37
@jasonblais I'm curious to get your thoughts on this issue. In summary, `matterhorn` (a terminal client) has some features to make it easy to use the local web browser to open attachments. But we're running into a problem because MatterMost serves such attachments with `Content-Disposition: attachment` and this forces the browser to prompt the user to download the attachment. Many attachments *are* viewable, though (e.g. images, PDFs) so having to download them first is undesirable. Is there any way we could get MatterMost to serve attachments in a way that permitted the user to view them in cases where the browser can, and download them otherwise?

**Comment by jasonblais** [comment] 2017-02-21 13:48
Thanks @jtdaugherty,

I think if you click an image or PDF file attachment, it opens a preview window for them first and a subsequent click downloads it.

Maybe I'm misunderstanding the question?

**Comment by jtdaugherty** [comment] 2017-02-21 16:37
The issue is that the server response given by `/api/v3/teams/<teamid>/files/get/...` always forces the browser to ask the user where to save the file (see above for details), and we're wondering if 1) there is a way around this that you know about and 2) if not, if we could please *have* a way around this. :)

**Comment by aisamanra** [comment] 2017-02-21 19:18
@jasonblais I think I should clarify that, because we're working on an alternate, non-web-based client, we're not touching the web UI at all, as all our interaction with Mattermost goes through the API. The preview window in the current MatterMost front-end is implemented by dynamically loading the attachment with JavaScript. Unfortunately, by virtue of being a standalone, terminal-based client, we don't have the ability to do this: we had hoped we could simply prompt the user to open a URL in the browser that would display the image, and as it stands there's no way _through the API_ to do this.

**Comment by jasonblais** [comment] 2017-02-28 05:35
@jtdaugherty @aisamanra I've chatted with our devs and we'll plan to add this support with the new APIv4 file endpoints. We have a contributor working on the file endpoints with the first of the four PRs submitted here: https://github.com/mattermost/platform/pull/5553

You can track the progress for the file endpoints here: https://docs.google.com/spreadsheets/d/1nPoLgwh_9zRFECpqRUZAKIWihCmX27pnDtFGLtG_WnY/edit#gid=1577458670

We'd expect this to be available on the next Mattermost server release (3.7 on March 16th).

**Comment by jtdaugherty** [comment] 2017-02-28 21:23
@jasonblais it looks like the endpoint you mentioned is for a thumbnail, but the endpoint that would help us most here is an endpoint that lets us download **the entire file** (not a thumbnail) without the `Content-Disposition: attachment` response header. Is that what this does, despite its name? Or is this something else entirely?

**Comment by jtdaugherty** [comment] 2017-03-20 17:32
I recall an out-of-band conversation with @aisamanra in which we established that a nice solution to this problem would be to have `matterhorn` fetch the attachment, store it in a temporary directory, and then use the URL opener command to open a local file URL. That avoids the `Content-Disposition` issue entirely *and* does the right thing with regard to authentication state by using `matterhorn`'s session instead of assuming that the user has also logged in in the browser.

**Comment by jasonblais** [comment] 2017-03-21 04:16
Hey @jtdaugherty - and sorry, I missed your earlier reply.

Here are all the file endpoints for references, with one where you can get the file itself (not just the thumbnail): https://api.mattermost.com/v4/#tag/files

Let me know if there's anything we can help with. If you don't hear a response, don't hesitate to reach out at https://pre-release.mattermost.com/core/channels/apiv4

**Comment by dagit** [comment] 2017-04-26 18:55
This is now done in the `server/3.8.1` branch and we can close it when that gets merged.

**Closed** 2017-05-10 17:35 UTC
Labels: low-hanging-fruit
