### ISSUE TITLE
users unable to open multi-user DM after recent upgrade of Mattermost server to 4.7.2

### ISSUE THREAD

**Issue by numericillustration** [matterhorn-chat/matterhorn#365] opened 2018-03-08 19:11 UTC
```
An unexpected error has occurred! The exception encountered was:
MattermostError {mattermostErrorId =
"store.sql_channel.save_channel.previously.app_error",
mattermostErrorMessage = "A channel with that URL was previously
created", mattermostErrorRequestId = "ztodmao77bratfnmfgfebb7r3c",
mattermostErrorStatusCode = 400, mattermostErrorIsOAuth = False}
Please report this error at
https://github.com/matterhorn-chat/matterhorn/issues
```

The action our user tried to take was (not the actual usernames):
`/group-msg <user1> <user2>`

additionally <user1> attempted to create the group DM in the web version of Mattermost chat and instead of getting any meaningful error or getting the group DM open, they were redirected to Town Square.

**Comment by jtdaugherty** [comment] 2018-03-08 19:14
Thanks for the report!

**Comment by jtdaugherty** [comment] 2018-03-08 23:53
What version of Matterhorn was used to trigger this?

**Comment by jtdaugherty** [comment] 2018-03-23 23:32
@numericillustration Can you provide some more context to help us track this down? Here's what would be very helpful:
 * The number of users involved (say, two, if one person took an action and another observed this error), along with the clients they were using and the client versions.
 * The sequence of events that took place, so we can reproduce the problem.

**Comment by jtdaugherty** [comment] 2018-04-04 21:17
@numericillustration Since we cannot reproduce this problem and you have not provided the requested information, we'll close this for now. Please feel free to re-open if you encounter the problem again and can help us reproduce it!

**Closed by jtdaugherty** 2018-04-04 21:17 UTC
Labels: bug
