### ISSUE TITLE
Cloning submodules fails

### ISSUE THREAD

**Issue by southerntofu** [matterhorn-chat/matterhorn#606] opened 2020-04-19 23:41 UTC
Hi!

I wanted to setup matterhorn but this proved complicated because for some reason the cloning of submodule fails:

```
southerntofu@thunix:~$ git clone --recursive https://github.com/matterhorn-chat/matterhorn/
Cloning into 'matterhorn'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 16352 (delta 31), reused 39 (delta 19), pack-reused 16278
Receiving objects: 100% (16352/16352), 4.99 MiB | 7.61 MiB/s, done.
Resolving deltas: 100% (12423/12423), done.
Submodule 'submodules/mattermost-api' (git@github.com:matterhorn-chat/mattermost-api.git) registered for path 'submodules/mattermost-api'
Submodule 'submodules/mattermost-api-qc' (git@github.com:matterhorn-chat/mattermost-api-qc.git) registered for path 'submodules/mattermost-api-qc'
Cloning into '/home/southerntofu/matterhorn/submodules/mattermost-api'...
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:matterhorn-chat/mattermost-api.git' into submodule path '/home/southerntofu/matterhorn/submodules/mattermost-api' failed
Failed to clone 'submodules/mattermost-api'. Retry scheduled
Cloning into '/home/southerntofu/matterhorn/submodules/mattermost-api-qc'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:matterhorn-chat/mattermost-api-qc.git' into submodule path '/home/southerntofu/matterhorn/submodules/mattermost-api-qc' failed
Failed to clone 'submodules/mattermost-api-qc'. Retry scheduled
Cloning into '/home/southerntofu/matterhorn/submodules/mattermost-api'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:matterhorn-chat/mattermost-api.git' into submodule path '/home/southerntofu/matterhorn/submodules/mattermost-api' failed
Failed to clone 'submodules/mattermost-api' a second time, aborting
```

I've tried on two separate machines and they both error. I think this may be a problem on Github's side but i just wanted to let you know in case there's something you can think of that could explain it (maybe weird permissions on the repo?)

now i manually cloned submodules as normal repos and it compiles fine on Debian buster

thanks

**Comment by jtdaugherty** [comment] 2020-04-20 00:07
This is because the submodules assume an SSH cloning URL and a GitHub account (duplicate of https://github.com/matterhorn-chat/matterhorn/issues/536). Thanks!

**Closed by jtdaugherty** 2020-04-20 00:07 UTC
