### ISSUE TITLE
Spell-checking support

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#227] opened 2017-05-06 15:36 UTC
Add support for spell-checking so that users can be notified when their message input contains spelling errors. This needs a design discussion prior to implementation so that this ticket can be filled out with a concrete plan (backend choice, UI behavior, etc.).

**Comment by dagit** [comment] 2017-05-06 17:22
Duplicate of #133

**Closed by dagit** 2017-05-06 17:22 UTC
Labels: enhancement
