### ISSUE TITLE
Option to use nickname as display name

### ISSUE THREAD

**Issue by kellymclaughlin** [matterhorn-chat/matterhorn#311] opened 2017-09-01 23:31 UTC
The desktop client for MM allows you to use nicknames for display and fall back the the user name if no nickname is set. This would be nice to also have in matterhorn. I'd be willing to work on this if others think it's a good idea as well.

**Comment by jtdaugherty** [comment] 2017-09-01 23:32
Thanks for the issue - this is a duplicate of https://github.com/matterhorn-chat/matterhorn/issues/265.

**Closed by jtdaugherty** 2017-09-01 23:32 UTC
