### ISSUE TITLE
It is difficult to get a markdown url from the topic

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#767] opened 2022-06-07 17:00 UTC
Hello; many of my coworkers like to use the markdown 'hide the URL' formatting in channel topics.

The `C-o` keybinding does not show these URLs.

The `/topic` command brings up a very small modal dialog window that doesn't show very long URLs that are common to Google docs.

Is there a better way to get the contents of these markdown 'pretty URLs'?

Thanks
![channel_topic](https://user-images.githubusercontent.com/5447148/172440231-5cdf4c46-d5f4-43f7-8446-6af2f1c0532c.png)
![no_urls_found](https://user-images.githubusercontent.com/5447148/172440248-7f9688e0-8f3d-42da-bb39-7c334f7e3b41.png)

**Comment by jtdaugherty** [comment] 2022-06-07 21:50
I am referring to mouse mode in Matterhorn, which enables mouse event detection in the terminal. Try setting `enableMouseMode: True` in `~/.config/matterhorn/config.ini` and see if that helps.

**Comment by setharnold** [comment] 2022-06-09 01:53
On Tue, Jun 07, 2022 at 02:50:48PM -0700, Jonathan Daugherty wrote:
> I am referring to mouse mode in Matterhorn, which enables mouse event
> detection in the terminal. Try setting `enableMouseMode: True` in
> `~/.config/matterhorn/config.ini` and see if that helps.

I tried `enableMouseMode = True` (to match the other entries in my
config), and that didn't seem to change anything: single click on the
`<Migration Doc>` section of the topic didn't appear to do anything;
double-click selected the word `Migration`; right-click selected from
the beginning of the line to the point where I clicked. It all felt like
standard terminal things.

I don't think that worked :(

The snap info has version number: 50200.16.0-1-gf45d1366 -- I hope this
translates well :)

Thanks

**Comment by jtdaugherty** [comment] 2022-06-09 02:28
Okay. It might be the case that your terminal just doesn't support mouse events. I couldn't definitely confirm this by googling, however. Mouse mode support is not especially exotic; many terminal emulators that have been around for decades tend to support it. Could you try a different terminal emulator, such as `xterm`, with that config setting enabled? That would help us narrow this down.

**Comment by setharnold** [comment] 2022-06-10 02:31
On Wed, Jun 08, 2022 at 07:28:35PM -0700, Jonathan Daugherty wrote:
> Okay. It might be the case that your terminal just doesn't support mouse
> events. I couldn't definitely confirm this by googling, however. Mouse

It supports *some* sort of mouse pass-through, eg the w3m browser lets me
use the mouse to click links, focus text fields, etc. (The consequence is
that it also breaks select, so I actually really dislike the w3m mouse
integration.)

> mode support is not especially exotic; many terminal emulators that have
> been around for decades tend to support it. Could you try a different
> terminal emulator, such as `xterm`, with that config setting enabled?
> That would help us narrow this down.

Excellent idea! I'm sorry I didn't think of it. The mouse sort-of works
in xterm:

- Clicking channel names in the sidebar on the left will change to that
  channel. Neat! I found it by accident.

- Clicking the `<Migration doc>` link in the topic of the channel didn't
  do anything.

  Just for completeness, I don't see any evidence of the snap sandboxing
  denying it via `journalctl -f` or `tail -F /var/log/audit/audit.log`.

- The mouse can't select text or paste text.

Thanks

**Comment by jtdaugherty** [comment] 2022-06-10 02:37
> The consequence is that it also breaks select, so I actually really dislike the w3m mouse integration.

This is because of the fact that mouse mode is enabled; terminal emulators I've used often provide a modifier that you can press to bypass mouse mode to select the way you are describing. You might try holding Alt or something like that to see if your terminal emulator lets you do that. (Or check the docs.)

But! That's exactly the confirmation I was hoping for; it sounds like the terminal *does* support mouse input the way that Matterhorn needs it to.

> Clicking the `<Migration doc>` link in the topic of the channel didn't do anything.

I just remembered that I fixed a bug in the development version that should resolve this. It fixed clickable links in the channel header, specifically. Thanks for doing a bit of extra testing to confirm!

Also: check out the mouse mode section of the User Guide. It talks about all of the ways that you can interact with Matterhorn with a mouse.

> The mouse can't select text or paste text.

That's right; that gets back to exactly the thing I described above with w3m. You'll need to find out whether your emulator supports a bypass modifier key that you can hold while selecting.

**Comment by jtdaugherty** [comment] 2022-06-10 02:49
To explicitly close the loop on the original request: I'll think about a way to make the channel header's URLs available for the case when mouse mode is not enabled. In the mean time, there's a bug in the released version of Matterhorn that specifically prevents channel header links from being clickable (which I am pretty sure is a regression). That bug is fixed in the development version of Matterhorn, but the next release date isn't clear because there are huge changes underway in the development version that will need to be fully tested before I can put out another release.

**Comment by setharnold** [comment] 2022-06-10 03:17
On Thu, Jun 09, 2022 at 07:37:20PM -0700, Jonathan Daugherty wrote:
> This is because of the fact that mouse mode is enabled; terminal
> emulators I've used often provide a modifier that you can press to
> bypass mouse mode to select the way you are describing. You might try
> holding Alt or something like that to see if your terminal emulator lets
> you do that. (Or check the docs.)

Aha! I've never seen this before. (To be fair, w3m was the only one I've
seen use it, and it mostly annoyed me, so I didn't put much effort it.)

Shift+select works great in w3m.

> But! That's exactly the confirmation I was hoping for; it sounds like
> the terminal *does* support mouse input the way that Matterhorn needs it
> to.

I'm not sure it does, though -- clicking on the channels doesn't switch to
the clicked channel, clicking on user names doesn't open a query window
with them, etc. I really don't understand the terminal features area well.
I found what I believe to the terminfo file for my terminal (the
rxvt-unicode package in Ubuntu, derived from Debian, relies upon the
ncurses-base package to provide the /lib/terminfo/r/rxvt-unicode file.)
I've put what I believe is the input file at the end of this message.

> I just remembered that I fixed a bug in the development version that
> should resolve this. It fixed clickable links in the channel header,
> specifically. Thanks for doing a bit of extra testing to confirm!

Aha! So, I could get this feature right now if I used your binaries. :)

> Also: check out the mouse mode section of the User Guide. It talks about
> all of the ways that you can interact with Matterhorn with a mouse.

Wow, that's very comprehensive. Nice.

> > The mouse can't select text or paste text.
> 
> That's right; that gets back to exactly the thing I described above with
> w3m. You'll need to find out whether your emulator supports a bypass
> modifier key that you can hold while selecting.

Now that's the question.. would I want to remember that *this* terminal is
the odd one out of all my terminals?

Can the mouse mode be toggled at runtime? If not, could it? (If yes, do
you want me to file a new issue?)

Thanks


Here's the file I think is the input source for the terminfo. It's from:

ncurses/ncurses_6.2-0ubuntu2/debian/rxvt-unicode.ti

`ncurses` source package; binary package version `6.2-0ubuntu2`; file
`debian/rxvt-unicode.ti`.


```
# From: Thomas Dickey ***@***.***> 04 Oct 1997
# Updated: Özgür Kesim ***@***.***> 02 Nov 1997
# Updated: Marc Lehmann ***@***.***>, 17 Feb 2005
# Updated: Marc Lehmann ***@***.***>, 04 Nov 2008: change init/reset sequences
# Updated: Marc Lehmann ***@***.***>, 24 Nov 2014: implement cvvis as blinking cursor
# Updated: Marc Lehmann ***@***.***>, 13 Dec 2014: removed superfluous 0 from sgr
rxvt-unicode|rxvt-unicode terminal (X Window System),
	am,
	bce,
	eo,
	km,
	msgr,
	xenl,
	hs,
	cols#80,
	it#8,
	lines#24,
	acsc=``aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~-A.B+C\,D0EhFiG,
	bel=^G,
	blink=\E[5m,
	bold=\E[1m,
	clear=\E[H\E[2J,
	civis=\E[?25l,
	cnorm=\E[?12l\E[?25h,
	cvvis=\E[?12;25h,
	cr=^M,
	csr=\E[%i%p1%d;%p2%dr,
	cub=\E[%p1%dD,
	cub1=^H,
	cud=\E[%p1%dB,
	cud1=^J,
	cuf=\E[%p1%dC,
	cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH,
	cuu=\E[%p1%dA,
	cuu1=\E[A,
	dch=\E[%p1%dP,
	dch1=\E[P,
	dl=\E[%p1%dM,
	dl1=\E[M,
	ed=\E[J,
	el=\E[K,
	el1=\E[1K,
	flash=\E[?5h$<20/>\E[?5l,
	home=\E[H,
	hpa=\E[%i%p1%dG,
	ht=^I,
	hts=\EH,
	ich=\E[%p1%d@,
	ich1=\E[@,
	il=\E[%p1%dL,
	il1=\E[L,
	ind=^J,
	is1=\E[\041p,
	is2=\E[r\E[m\E[2J\E[?7;25h\E[?1;3;4;5;6;9;66;1000;1001;1049l\E[4l,
	kDC=\E[3$,
	kDC5=\E[3\^,
	kDC6=\E[3@,
	kDN=\E[b,
	kDN5=\EOb,
	kIC=\E[2$,
	kIC5=\E[2\^,
	kIC6=\E[2@,
	kEND=\E[8$,
	kEND5=\E[8\^,
	kEND6=\E[8@,
	kFND=\E[1$,
	kFND5=\E[1\^,
	kFND6=\E[1@,
	kHOM=\E[7$,
	kHOM5=\E[7\^,
	kHOM6=\E[7@,
	kLFT=\E[d,
	kLFT5=\EOd,
	kNXT=\E[6$,
	kNXT5=\E[6\^,
	kNXT6=\E[6@,
	kPRV=\E[5$,
	kPRV5=\E[5\^,
	kPRV6=\E[5@,
	kRIT=\E[c,
	kRIT5=\EOc,
	kUP=\E[a,
	kUP5=\EOa,
	kbs=\177,
	ka1=\EOw,
	ka3=\EOy,
	kb2=\EOu,
	kc1=\EOq,
	kc3=\EOs,
	kcbt=\E[Z,
	kcub1=\E[D,
	kcud1=\E[B,
	kcuf1=\E[C,
	kcuu1=\E[A,
	kdch1=\E[3~,
	kel=\E[8\^,
	kend=\E[8~,
	kent=\EOM,
	kf1=\E[11~,
	kf10=\E[21~,
	kf11=\E[23~,
	kf12=\E[24~,
	kf13=\E[25~,
	kf14=\E[26~,
	kf15=\E[28~,
	kf16=\E[29~,
	kf17=\E[31~,
	kf18=\E[32~,
	kf19=\E[33~,
	kf2=\E[12~,
	kf20=\E[34~,
	kf3=\E[13~,
	kf4=\E[14~,
	kf5=\E[15~,
	kf6=\E[17~,
	kf7=\E[18~,
	kf8=\E[19~,
	kf9=\E[20~,
	kfnd=\E[1~,
	khome=\E[7~,
	kich1=\E[2~,
	kmous=\E[M,
	knp=\E[6~,
	kpp=\E[5~,
	kslt=\E[4~,
	rc=\E8,
	rev=\E[7m,
	ri=\EM,
	rmso=\E[27m,
	rmul=\E[24m,
	rs1=\Ec,
	rs2=\E[r\E[m\E[?7;25h\E[?1;3;4;5;6;9;66;1000;1001;1049l\E[4l,
	sgr0=\E[m\E(B,
	enacs=,
	smacs=\E(0,
	rmacs=\E(B,
	smso=\E[7m,
	smul=\E[4m,
	tbc=\E[3g,
	vpa=\E[%i%p1%dd,
	colors#88,
	pairs#7744,
	btns#5,
	lm#0,
	ccc,
	npc,
	mc5i,
	ncv#0,
	mir,
	xon,
	bw,
	ech=\E[%p1%dX,
	mc0=\E[i,
	mc4=\E[4i,
	mc5=\E[5i,
	sitm=\E[3m,
	ritm=\E[23m,
	smam=\E[?7h,
	rmam=\E[?7l,
	smir=\E[4h,
	rmir=\E[4l,
	smcup=\E[?1049h,
	rmcup=\E[r\E[?1049l,
	smkx=\E=,
	rmkx=\E>,
	indn=\E[%p1%dS,
	rin=\E[%p1%dT,
	sgr=\E[%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m%?%p9%t\E(0%e\E(B%;,
	op=\E[39;49m,
	setaf=\E[38;5;%p1%dm,
	setab=\E[48;5;%p1%dm,
	setf=%?%p1%{7}%>%t\E[38;5;%p1%dm%e\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m%;,
	setb=%?%p1%{7}%>%t\E[48;5;%p1%dm%e\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m%;,
	initc=\E]4;%p1%d;rgb\:%p2%{65535}%*%{1000}%/%4.4X/%p3%{65535}%*%{1000}%/%4.4X/%p4%{65535}%*%{1000}%/%4.4X\E\\,
	sc=\E7,
	s0ds=\E(B,
	s1ds=\E(0,
	s2ds=\E*B,
	s3ds=\E+B,
	u6=\E[%i%d;%dR,
	u7=\E[6n,
	u8=\E[?1;2c,
	u9=\E[c,
	tsl=\E]2;,
	fsl=\007,
	dsl=\E]2;\007,

rxvt-unicode-256color|rxvt-unicode terminal with 256 colors (X Window System),
	colors#256,
	pairs#32767,
	use=rxvt-unicode,
```

**Comment by setharnold** [comment] 2022-06-10 03:21
On Thu, Jun 09, 2022 at 07:49:58PM -0700, Jonathan Daugherty wrote:
> To explicitly close the loop on the original request: I'll think about a
> way to make the channel header's URLs available for the case when mouse
> mode is not enabled. In the mean time, there's a bug in the released

Excellent; thanks again, it's been a pleasure as always :)

**Comment by jtdaugherty** [comment] 2022-06-10 03:24
> Aha! So, I could get this feature right now if I used your binaries. :)

Just to clarify, the latest released version still has the bug. It's the development version (unreleased) that has the fix.

**Comment by jtdaugherty** [comment] 2022-06-10 03:36
> Shift+select works great in w3m.

Great! Then that will work for you in any application that uses mouse mode (tmux, Matterhorn, etc.).

> clicking on the channels doesn't switch to the clicked channel, clicking on user names doesn't open a query window with them, etc.

I'm confused by this, because earlier you said

> Clicking channel names in the sidebar on the left will change to that channel. Neat! I found it by accident.

> Now that's the question.. would I want to remember that *this* terminal is the odd one out of all my terminals?

What do you mean by this? This particular terminal emulator, urxvt, will support Shift-selection for any application that otherwise would intercept the mouse input. I don't know how that makes it the odd one out. Other terminals like xterm or iTerm2 have similar features.

> Can the mouse mode be toggled at runtime? If not, could it? (If yes, do you want me to file a new issue?)

No, it cannot currently be toggled at runtime. Feel free to open a ticket about that. I'd have to do some investigation to see whether it could be done.

**Comment by jtdaugherty** [comment] 2022-06-10 20:42
@setharnold FYI, mouse mode can now be toggled via command in [this patch](https://github.com/matterhorn-chat/matterhorn/commit/34230f83e74c9efb0b9ffba5d946b2859714c50f) and that will go out in the next release.

**Comment by setharnold** [comment] 2022-06-11 00:32
On Thu, Jun 09, 2022 at 08:36:24PM -0700, Jonathan Daugherty wrote:
> > clicking on the channels doesn't switch to the clicked channel,
> > clicking on user names doesn't open a query window with them, etc.
> 
> I'm confused by this, because earlier you said
> 
> > Clicking channel names in the sidebar on the left will change to that
> > channel. Neat! I found it by accident.
> > Now that's the question.. would I want to remember that *this*
> > terminal is the odd one out of all my terminals?
> 
> What do you mean by this? This particular terminal emulator, urxvt, will
> support Shift-selection for any application that otherwise would
> intercept the mouse input. I don't know how that makes it the odd one
> out. Other terminals like xterm or iTerm2 have similar features.

Ah, sorry, I see I wasn't very precise here.

At the moment I've got 35 terminals open; in all of them, double-clicking
a word will select the word, triple-clicking will select a line. Dragging
will select from start to finish, etc.

Firefox acts similar.

If I run matterhorn with mouse mode enabled all the time, it'll *look*
just like all my other terminals, but it won't behave like it, because
double-clicking won't select words. (Triple-click is inconsistent and not
super-useful in matterhorn. Oh well.)

> > Can the mouse mode be toggled at runtime? If not, could it? (If yes,
> > do you want me to file a new issue?)
> 
> No, it cannot currently be toggled at runtime. Feel free to open a
> ticket about that. I'd have to do some investigation to see whether it
> could be done.

Heh, I see I was too slow for this :) Thanks!

**Comment by jtdaugherty** [comment] 2022-06-11 00:52
> If I run matterhorn with mouse mode enabled all the time, it'll *look* just like all my other terminals, but it won't behave like it, because double-clicking won't select words. (Triple-click is inconsistent and not super-useful in matterhorn. Oh well.)

That's right; you'd just need to remember that a bypass key is needed for that application.

**Comment by jtdaugherty** [comment] 2022-06-28 19:42
@setharnold I wanted to mention that the latest release (50200.17.0) includes the new `/toggle-mouse-input` command as well as the channel topic URL clicking bugfix. With that, I'm going to close this. Thanks!

**Closed by jtdaugherty** 2022-06-28 19:42 UTC
