### ISSUE TITLE
Ability to accept Mattermost message URLs

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#661] opened 2020-08-31 14:19 UTC
My colleagues often use the 'copy link' functionality for messages in Mattermost.  At the moment, I have no choice but to open these in a browser.  I don't know if it's possible, but it'd be awesome if I could pass them to Matterhorn instead and have it jump to the message if it's a Mattermost server & team I'm already connected to.

(There's a little more context about these links in #660)

**Comment by jtdaugherty** [comment] 2020-08-31 15:43
I believe you are referring to message "permalinks" - is that right?

**Comment by jtdaugherty** [comment] 2020-08-31 15:46
Ah yes, I see from the URL pattern you mentioned in #660 that this is about permalinks. Thanks! This is a duplicate of #562.

**Closed by jtdaugherty** 2020-08-31 15:46 UTC
