### ISSUE TITLE
Add support for mattermost 4.0

### ISSUE THREAD

**Issue by Hanzei** [matterhorn-chat/matterhorn#290] opened 2017-07-21 07:27 UTC
When starting matterhorn and trying to connect to a mattermost 4.0 server, the program crashes with:
```
matterhorn: JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.event:
Unknown websocket message: \"channel_viewed\"", jsonDecodeExceptionJSON = "{\"event\":\"channel_viewed\",\"data\":{\"channel_id\":\"ckadnzmh3tdb8x85qsf5ophawr\"},\"broadcast\":{\"omit_users\":null,\"user_id\":\"psdu9ssrsir6ibixri9thcia9w\",\"channel_id\":\"\",\"team_id\":\"\"},\"seq\":1}"}
```

**Comment by jtdaugherty** [comment] 2017-07-21 14:52
Thanks for the report! This is a duplicate of #288.

**Closed by jtdaugherty** 2017-07-21 14:52 UTC
