### ISSUE TITLE
Held down key combined with Alt/Meta ends up losing the Alt/Meta

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#721] opened 2021-06-24 18:44 UTC
If for example, I edit a message I have sent, hold down Alt/Meta and then also hold down 'b', almost inevitably, I end up with a line that says 'b' or 'bb', i.e. the fact that Alt/Meta is held down seem to get lost.  If I hold down Alt/Meta and press and release 'b' carefully multiple times this doesn't happen.  I'm using Ubuntu 20.10 with xfce4-terminal and matterhorn 50200.13.0-2-g6fefdd02 from the snap.  I don't see this behaviour with other applications (e.g. bash) in the same terminal, FWIW.

**Comment by jtdaugherty** [comment] 2021-06-24 18:47
Have you tried this in terminal emulators other than `xfce4-terminal`?

**Comment by jtroup** [comment] 2021-06-25 00:52
Broken:
 * gnome-terminal
 * mate-terminal
 * termit
 * termonad
 * tilix
 * xfce4-terminal

Working:
 * kitty
 * rxvt-unicode
 * stterm
 * terminology

Did a bit more digging and all the broken ones appear to be VTE based, whereas all the ones where it works are not based on VTE.

```
root@malefic:~# for i in gnome-terminal.real mate-terminal termit termonad tilix xfce4-terminal kitty rxvt-unicode stterm terminology; do echo -n ${i}": "; if ldd /usr/bin/${i} | grep -q libvte; then echo uses VTE; else echo no VTE; fi; done
gnome-terminal.real: uses VTE
mate-terminal: uses VTE
termit: uses VTE
termonad: uses VTE
tilix: uses VTE
xfce4-terminal: uses VTE
kitty: no VTE
rxvt-unicode: no VTE
stterm: no VTE
terminology: no VTE
root@malefic:~# 
```

**Comment by jtdaugherty** [comment] 2021-06-25 01:06
I would venture to guess that you have been using `matterhorn` for quite a while. When did this behavior start?

**Comment by jtdaugherty** [comment] 2021-06-25 01:07
(Thank you for doing a lot of research on where this works and doesn't!)

**Comment by jtdaugherty** [comment] 2021-06-25 01:08
Can you say a bit more about exactly what you mean here:

> If I hold down Alt/Meta and press and release 'b' carefully multiple times this doesn't happen

How is what you're doing here different than:

> hold down Alt/Meta and then also hold down 'b', almost inevitably, I end up with a line that says 'b' or 'bb'

**Comment by jtroup** [comment] 2021-06-25 01:28
> I would venture to guess that you have been using `matterhorn` for quite a while. When did this behavior start?

It's been present in Matterhorn since I started using it (~14 months ago).  I don't have a really good reason as to why I haven't reported until now other than: a) it's elusive and not 100% reproducible, b) it's got a work around (use arrow keys) and c) I only really run into it while editing messages which I don't do super frequently.

> Can you say a bit more about exactly what you mean here:
> 
> > If I hold down Alt/Meta and press and release 'b' carefully multiple times this doesn't happen

Let's call this (1)
 
> How is what you're doing here different than:
> 
> > hold down Alt/Meta and then also hold down 'b', almost inevitably, I end up with a line that says 'b' or 'bb'

And this (2).

In both cases, Alt/Meta is held down the whole time by my left thumb.  (Also in both cases, I start with Alt/Meta)

In case (1), I am using a finger to tap and release 'b'; if I go too fast and don't leave between the release and the next tap, the bug will trigger.  If I go slowly/carefully, the bug will never trigger.

In case (2), I am using a finger to hold down 'b' the entire time; at some point, most of the time, the bug will trigger.

**Comment by jtdaugherty** [comment] 2021-12-07 18:19
Given that we haven't been able to reproduce this, I'm going to close it. As a behavior that is not easily reproducible, it isn't clear exactly where the problem is likely to be (i.e. `vty`, `matterhorn`, terminal emulation libraries, etc.). If someone ends up getting more detailed information about this problem, let's definitely re-open and investigate.

**Closed by jtdaugherty** 2021-12-07 18:19 UTC
